const ai = [
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 0,
    packaging_issue: 0,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 100,
    hygiene_issue: 0,
    "missing food_issue": 100,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 50,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 30,
    freshness_issue: 20,
    "Staleness Issue": 90,
    hardness_issue: 0,
    spice_issue: 20,
    temperature_issue: 30,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 20,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 80,
    "delivery timing_issue": 80,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 20,
    "Staleness Issue": 90,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 90,
    "missing food_issue": 90,
    oiliness_issue: 20,
    "out of stock_issue": 70,
    foreign_object_issue: 50,
  },
  {
    quality_issue: 30,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 70,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 50,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 100,
    hygiene_issue: 0,
    "missing food_issue": 100,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 85,
    taste_issue: 95,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 90,
    cooking_issue: 70,
    freshness_issue: 60,
    "Staleness Issue": 85,
    hardness_issue: 0,
    spice_issue: 50,
    temperature_issue: 70,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 60,
    quantity_issue: 50,
    taste_issue: 90,
    packaging_issue: 40,
    "delivery timing_issue": 70,
    price_issue: 80,
    cooking_issue: 30,
    freshness_issue: 20,
    "Staleness Issue": 70,
    hardness_issue: 30,
    spice_issue: 40,
    temperature_issue: 70,
    wrong_food_issue: 90,
    hygiene_issue: 50,
    "missing food_issue": 70,
    oiliness_issue: 60,
    "out of stock_issue": 30,
    foreign_object_issue: 10,
  },
  {
    quality_issue: 25,
    quantity_issue: 0,
    taste_issue: 70,
    packaging_issue: 30,
    "delivery timing_issue": 0,
    price_issue: 20,
    cooking_issue: 0,
    freshness_issue: 55,
    "Staleness Issue": 50,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 20,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 60,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 70,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 70,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 90,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 80,
  },
  {
    quality_issue: 60,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    delivery_timing_issue: 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    staleness_issue: 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    missing_food_issue: 0,
    oiliness_issue: 0,
    out_of_stock_issue: 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 80,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 60,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 60,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 80,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 50,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 90,
    "delivery timing_issue": 90,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 70,
    quantity_issue: 80,
    taste_issue: 90,
    packaging_issue: 10,
    "delivery timing_issue": 10,
    price_issue: 20,
    cooking_issue: 60,
    freshness_issue: 30,
    "Staleness Issue": 80,
    hardness_issue: 90,
    spice_issue: 50,
    temperature_issue: 70,
    wrong_food_issue: 0,
    hygiene_issue: 60,
    "missing food_issue": 0,
    oiliness_issue: 50,
    "out of stock_issue": 0,
    foreign_object_issue: 20,
  },
  {
    quality_issue: 30,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 70,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 60,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 80,
    hygiene_issue: 90,
    "missing food_issue": 70,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 80,
  },
  {
    quality_issue: 30,
    quantity_issue: 80,
    taste_issue: 95,
    packaging_issue: 10,
    "delivery timing_issue": 0,
    price_issue: 20,
    cooking_issue: 80,
    freshness_issue: 20,
    "Staleness Issue": 80,
    hardness_issue: 75,
    spice_issue: 20,
    temperature_issue: 75,
    wrong_food_issue: 90,
    hygiene_issue: 80,
    "missing food_issue": 90,
    oiliness_issue: 30,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 90,
    freshness_issue: 0,
    "Staleness Issue": 90,
    hardness_issue: 90,
    spice_issue: 0,
    temperature_issue: 90,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 90,
    taste_issue: 70,
    packaging_issue: 80,
    "delivery timing_issue": 90,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 75,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 80,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 40,
    "Staleness Issue": 60,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 70,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 75,
    quantity_issue: 90,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 60,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 80,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 90,
    price_issue: 0,
    cooking_issue: 80,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 70,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 70,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 90,
    freshness_issue: 0,
    "Staleness Issue": 90,
    hardness_issue: 90,
    spice_issue: 0,
    temperature_issue: 90,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 70,
    packaging_issue: 60,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 50,
    freshness_issue: 10,
    "Staleness Issue": 80,
    hardness_issue: 90,
    spice_issue: 20,
    temperature_issue: 0,
    wrong_food_issue: 80,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 70,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 70,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 10,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 30,
    taste_issue: 60,
    packaging_issue: 25,
    "delivery timing_issue": 40,
    price_issue: 10,
    cooking_issue: 20,
    freshness_issue: 50,
    "Staleness Issue": 70,
    hardness_issue: 15,
    spice_issue: 45,
    temperature_issue: 35,
    wrong_food_issue: 60,
    hygiene_issue: 80,
    "missing food_issue": 50,
    oiliness_issue: 20,
    "out of stock_issue": 5,
    foreign_object_issue: 10,
  },
  {
    quality_issue: 100,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 100,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 50,
    packaging_issue: 80,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 70,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 70,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 100,
    taste_issue: 90,
    packaging_issue: 0,
    delivery_timing_issue: 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    staleness_issue: 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    missing_food_issue: 0,
    oiliness_issue: 0,
    out_of_stock_issue: 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 60,
    quantity_issue: 0,
    taste_issue: 75,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 70,
    cooking_issue: 80,
    freshness_issue: 50,
    "Staleness Issue": 80,
    hardness_issue: 70,
    spice_issue: 60,
    temperature_issue: 80,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 90,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 70,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 70,
    freshness_issue: 30,
    "Staleness Issue": 70,
    hardness_issue: 0,
    spice_issue: 30,
    temperature_issue: 70,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 30,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 90,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 60,
    taste_issue: 100,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 60,
    cooking_issue: 90,
    freshness_issue: 0,
    "Staleness Issue": 70,
    hardness_issue: 90,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 70,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 60,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 80,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 70,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 50,
    packaging_issue: 0,
    "delivery timing_issue": 90,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 80,
    hygiene_issue: 0,
    "missing food_issue": 70,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 70,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 70,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 90,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 60,
    quantity_issue: 90,
    taste_issue: 50,
    packaging_issue: 10,
    delivery_timing_issue: 20,
    price_issue: 0,
    cooking_issue: 80,
    freshness_issue: 40,
    staleness_issue: 70,
    hardness_issue: 80,
    spice_issue: 0,
    temperature_issue: 70,
    wrong_food_issue: 50,
    hygiene_issue: 30,
    missing_food_issue: 10,
    oiliness_issue: 60,
    out_of_stock_issue: 0,
    foreign_object_issue: 10,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 80,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 20,
    freshness_issue: 0,
    "Staleness Issue": 80,
    hardness_issue: 80,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: "0%",
    quantity_issue: "100%",
    taste_issue: "50%",
    packaging_issue: "0%",
    "delivery timing_issue": "0%",
    price_issue: "0%",
    cooking_issue: "0%",
    freshness_issue: "0%",
    "Staleness Issue": "0%",
    hardness_issue: "0%",
    spice_issue: "0%",
    temperature_issue: "0%",
    wrong_food_issue: "0%",
    hygiene_issue: "0%",
    "missing food_issue": "0%",
    oiliness_issue: "0%",
    "out of stock_issue": "0%",
    foreign_object_issue: "0%",
  },
  {
    quality_issue: 70,
    quantity_issue: 80,
    taste_issue: 90,
    packaging_issue: 60,
    delivery_timing_issue: 80,
    price_issue: 40,
    cooking_issue: 0,
    freshness_issue: 50,
    staleness_issue: 80,
    hardness_issue: 0,
    spice_issue: 20,
    temperature_issue: 40,
    wrong_food_issue: 70,
    hygiene_issue: 30,
    missing_food_issue: 60,
    oiliness_issue: 60,
    out_of_stock_issue: 0,
    foreign_object_issue: 80,
  },
  {
    quality_issue: 40,
    quantity_issue: 0,
    taste_issue: 80,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 90,
    freshness_issue: 10,
    "Staleness Issue": 70,
    hardness_issue: 60,
    spice_issue: 50,
    temperature_issue: 80,
    wrong_food_issue: 90,
    hygiene_issue: 60,
    "missing food_issue": 90,
    oiliness_issue: 60,
    "out of stock_issue": 0,
    foreign_object_issue: 60,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 0,
    packaging_issue: 0,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 95,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 90,
    freshness_issue: 0,
    "Staleness Issue": 90,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 85,
    packaging_issue: 20,
    "delivery timing_issue": 0,
    price_issue: 50,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 20,
    temperature_issue: 0,
    wrong_food_issue: 100,
    hygiene_issue: 0,
    "missing food_issue": 80,
    oiliness_issue: 10,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 80,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 90,
    taste_issue: 70,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 80,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 90,
    taste_issue: 70,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 70,
    packaging_issue: 50,
    "delivery timing_issue": 0,
    price_issue: 90,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 90,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 70,
    "missing food_issue": 0,
    oiliness_issue: 70,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 70,
    taste_issue: 95,
    packaging_issue: 0,
    delivery_timing_issue: 0,
    price_issue: 60,
    cooking_issue: 90,
    freshness_issue: 70,
    staleness_issue: 80,
    hardness_issue: 70,
    spice_issue: 50,
    temperature_issue: 70,
    wrong_food_issue: 100,
    hygiene_issue: 0,
    missing_food_issue: 100,
    oiliness_issue: 50,
    out_of_stock_issue: 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 90,
    taste_issue: 70,
    packaging_issue: 70,
    "delivery timing_issue": 60,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 90,
    "missing food_issue": 90,
    oiliness_issue: 70,
    "out of stock_issue": 0,
    foreign_object_issue: 90,
  },
  {
    quality_issue: 10,
    quantity_issue: 100,
    taste_issue: 70,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 50,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 50,
    hygiene_issue: 0,
    "missing food_issue": 100,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 50,
    quantity_issue: 70,
    taste_issue: 60,
    packaging_issue: 50,
    "delivery timing_issue": 50,
    price_issue: 0,
    cooking_issue: 50,
    freshness_issue: 0,
    "Staleness Issue": 50,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 70,
    hygiene_issue: 0,
    "missing food_issue": 70,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 80,
    taste_issue: 70,
    packaging_issue: 0,
    delivery_timing_issue: 0,
    price_issue: 90,
    cooking_issue: 60,
    freshness_issue: 0,
    staleness_issue: 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    missing_food_issue: 0,
    oiliness_issue: 0,
    out_of_stock_issue: 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 80,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 100,
    taste_issue: 80,
    packaging_issue: 30,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 0,
    packaging_issue: 0,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 100,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 85,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 80,
    delivery_timing_issue: 85,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 70,
    staleness_issue: 90,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    missing_food_issue: 0,
    oiliness_issue: 0,
    out_of_stock_issue: 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 90,
    taste_issue: 70,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 90,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 90,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 60,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 80,
    taste_issue: 100,
    packaging_issue: 10,
    "delivery timing_issue": 0,
    price_issue: 100,
    cooking_issue: 70,
    freshness_issue: 30,
    "Staleness Issue": 90,
    hardness_issue: 80,
    spice_issue: 60,
    temperature_issue: 70,
    wrong_food_issue: 70,
    hygiene_issue: 100,
    "missing food_issue": 90,
    oiliness_issue: 20,
    "out of stock_issue": 10,
    foreign_object_issue: 20,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 90,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 60,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 85,
    taste_issue: 95,
    packaging_issue: 50,
    "delivery timing_issue": 0,
    price_issue: 100,
    cooking_issue: 0,
    freshness_issue: 30,
    "Staleness Issue": 90,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 70,
    quantity_issue: 90,
    taste_issue: 80,
    packaging_issue: 10,
    "delivery timing_issue": 50,
    price_issue: 70,
    cooking_issue: 60,
    freshness_issue: 50,
    "Staleness Issue": 70,
    hardness_issue: 30,
    spice_issue: 50,
    temperature_issue: 60,
    wrong_food_issue: 40,
    hygiene_issue: 60,
    "missing food_issue": 70,
    oiliness_issue: 40,
    "out of stock_issue": 10,
    foreign_object_issue: 10,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 60,
    freshness_issue: 0,
    "Staleness Issue": 90,
    hardness_issue: 60,
    spice_issue: 20,
    temperature_issue: 40,
    wrong_food_issue: 80,
    hygiene_issue: 0,
    "missing food_issue": 80,
    oiliness_issue: 20,
    "out of stock_issue": 0,
    foreign_object_issue: 30,
  },
  {
    quality_issue: 0,
    quantity_issue: 60,
    taste_issue: 60,
    packaging_issue: 90,
    delivery_timing_issue: 0,
    price_issue: 90,
    cooking_issue: 0,
    freshness_issue: 0,
    staleness_issue: 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 90,
    missing_food_issue: 0,
    oiliness_issue: 0,
    out_of_stock_issue: 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 50,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 100,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 100,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 100,
    hygiene_issue: 0,
    "missing food_issue": 100,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 70,
    quantity_issue: 90,
    taste_issue: 90,
    packaging_issue: 10,
    "delivery timing_issue": 0,
    price_issue: 100,
    cooking_issue: 0,
    freshness_issue: 30,
    "Staleness Issue": 50,
    hardness_issue: 0,
    spice_issue: 10,
    temperature_issue: 0,
    wrong_food_issue: 70,
    hygiene_issue: 80,
    "missing food_issue": 80,
    oiliness_issue: 30,
    "out of stock_issue": 0,
    foreign_object_issue: 30,
  },
  {
    quality_issue: 80,
    quantity_issue: 70,
    taste_issue: 90,
    packaging_issue: 10,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 60,
    freshness_issue: 20,
    "Staleness Issue": 25,
    hardness_issue: 10,
    spice_issue: 30,
    temperature_issue: 80,
    wrong_food_issue: 70,
    hygiene_issue: 60,
    "missing food_issue": 90,
    oiliness_issue: 15,
    "out of stock_issue": 0,
    foreign_object_issue: 10,
  },
  {
    quality_issue: 50,
    quantity_issue: 90,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 90,
    taste_issue: 0,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 100,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 100,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 70,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 30,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 30,
    hygiene_issue: 0,
    "missing food_issue": 30,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 80,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 60,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 20,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 100,
  },
  {
    quality_issue: 90,
    quantity_issue: 0,
    taste_issue: 60,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 70,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 80,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 80,
    quantity_issue: 0,
    taste_issue: 70,
    packaging_issue: 60,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 40,
    freshness_issue: 50,
    "Staleness Issue": 60,
    hardness_issue: 0,
    spice_issue: 50,
    temperature_issue: 30,
    wrong_food_issue: 0,
    hygiene_issue: 40,
    "missing food_issue": 0,
    oiliness_issue: 30,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 80,
    quantity_issue: 70,
    taste_issue: 70,
    packaging_issue: 0,
    delivery_timing_issue: 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 40,
    staleness_issue: 60,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    missing_food_issue: 0,
    oiliness_issue: 0,
    out_of_stock_issue: 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 90,
    quantity_issue: 70,
    taste_issue: 80,
    packaging_issue: 95,
    "delivery timing_issue": 60,
    price_issue: 95,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 0,
    taste_issue: 90,
    packaging_issue: 0,
    "delivery timing_issue": 0,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    "Staleness Issue": 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 0,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
  {
    quality_issue: 0,
    quantity_issue: 100,
    taste_issue: 0,
    packaging_issue: 0,
    "delivery timing_issue": 100,
    price_issue: 0,
    cooking_issue: 0,
    freshness_issue: 0,
    stalenes_issue: 0,
    hardness_issue: 0,
    spice_issue: 0,
    temperature_issue: 0,
    wrong_food_issue: 0,
    hygiene_issue: 0,
    "missing food_issue": 100,
    oiliness_issue: 0,
    "out of stock_issue": 0,
    foreign_object_issue: 0,
  },
];

const reviews = [
  "i didn't get my food i didn't even get the right restaurant ",
  "way to salty! waaayy to salty and the fries are plain. they tasted like mcdonald's fries with no salt left over night. ",
  "nothing was right and got no refund",
  "they sent me meat on bread. i ordered the cheesehead. if you are thinking of ordering here dont. 3rd time this week. if you walk in they are fine. you order on doordash forget it. your order will 100% wrong or not what you wanted. youve been warned ",
  "will not again order from here.  the phili was so salty i couldn't eat it.  i ordered double the meat, which the meat was so dried out.  there are better cheese steaks at gas stations.  i also ordered a coke, which ended up being a $3 can of coke.  an absolute waste of money!!!",
  "order was wrong, $60 but $13 refund. garbage. save y money.",
  "i got a marinara meatball sub",
  "burnt onions rings hair in sandwich ",
  "don't pay for anything extra like extra cheese or toppings cause they won't add it to your food.",
  "it was too salty never will order from this place again",
  "lowkey wasn't that good, made me wanna finish it as fast as i can .",
  "sent the wrong order and doordash now takes 24 hours to even fix it this is a complete joke",
  "hard and dry ",
  "frito bandito and cheesesteak daddy were terrible ",
  "food was horrible sandwitch was ashes and my fries was frozen ",
  "only giving one star because it wasn't an option for none..... steak extremely overcooked/burnt and dry.... tried to submit a complaint with no response and no one answers the phone number listed.... definitely won't order ever again",
  "didn't get the right order",
  "only me combo does  not match description. small portion size no cheese i literally got the one with cheese and it has no cheese trying to get them to pick up i want refund",
  "i ordered the cheese head. in all fairness i did remove the onion and sourcraut, but what i received was barely a cheesesteak. of course it's not going to be overflowing like in the picture, but i at least expected it to be a decent amount of meat, even with the sourcraut removed. i wasn't expecting extra meat, but this sandwich is pathetic.",
  "the sandwich i received is not what i ordered, and on top of it the sandwich they did send me the meat is over cooked and dry. for the amount of time i had to wait past the estimated delivery time they could have gotten a one sandwich order correct. first time ordering, and is most likely the last unfortunately. ",
  "meat and buns were way overcooked.  entire meal was ruined, had to pick out what was edible off the top of the packs of meat.",
  "there was no meat in the burrito and the bagel was super super dry :/",
  "i upgraded to Onion rings and still got fries ",
  "   mid",
  "   everything inside of the burrito tasted stale or rotten. i couldn't even finish the first bite",
  "food cane cold and they did not even care to remake and sent hour hold??!! ",
  "   the promotion didnt work ",
  "burrito had no eggs, beef, or cheese. came with just tots and onions. was so disappointing after they took an extra 20 minutes beyond what was promised.",
  "actually leo's, overcooked, appetizer sized 20$ diner bull****",
  "wasn't a fan. ",
  "the quality of food was awful. the burritos mostly consist of the wrap and not enough filling. the side of hashbrowns were burnt and tasted very off. would not recommend.  ",
  "first time trying this place and my burrito is missing half the ingredients lol..",
  "The pasta taste like it was very undercooked and it was very chalky and pasty. And for $18. I expected a little bit more on the portion. ",
  "This is not really chicken marsala. It's a mushrooms sauce on fettuccine, with a salty, dry, grilled chicken breast on the top.  I was duped. Now you know.",
  "1st time trying this. they messed up the order and switched the burritos around.",
  "they made the wrong sandwich no lettuce no tomatoe no extra cheese.. and wayyyyy to much garlic",
  "ordered a pop's original and it should have had tomato sauce and provolone cheese.  sub came plain with some kind of yellow cheese.  not what i ordered at all!",
  "the sandwich had half meet for some reason. very disappointed and the fries were bot cooked properly either ",
  "hair in my food, too much onions",
  "the spaghetti was broken down to vermicelli length! sauce is subpar. ",
  "all i recieved were chciken wings",
  "the sheesehead had no cheese and extra things were added that were not listed as included toppings. what a shame",
  "food was dry over cook ",
  "Order never arrived! ",
  "the food was horrible!!! do not do it!!! the pasta wasn't drained and it was watery and a 5 year old could have made that!",
  "i received the wrong item. the item i received was terrible. the side of cheese sauce was canned nacho cheese. i would not recommend.",
  "just not what i thought it would look like or taste like.",
  "the fettuccine alfredo cost almost $20 and was the size of a lean cuisine. it was tiny.  ",
  "i've ordered from here twice and and haven't gotten meat on my burrito either time. lot of potential if they can get their orders right",
  "way to expensive not even good ",
  "terrible!  we paid the $6 upcharge for two pasta dishes and no chicken was included. the pasta dishes were overcooked and bland. save your money and eat elsewhere.",
  "forgot my cream cheese and the oj spilled all over everything so can't even eat it. ",
  "items were not included in my order aaand items were not as described either. ordered a bagel with cream cheese and didn't get the cream cheese. ordered the basic b*tch bowl and received hash browns instead of tots. i was very disappointed. won't be coming back.",
  "cheesehead came with no kraut, no onions, no whiz, pretty much nothing that was in the description. it did come with macaroni bites on the sandwhich. so kudos for trying",
  "first time i ordered everything was great but after that my food has been prepared poorly my fries are extremely low for the price i paid i'm very dissatisfied with what i received lately",
  "Absolutely awful  ",
  "   only got 1 of my 3 sandwhiches",
  "food was ice cold when it arrived 2 hours later  ",
  "   s",
  "the meals were all sent vegetarian and what we chose was all supposed to have meat. not worthy the price paid and very disappointing  ",
  "alfredo was bland but better than the green stuff ",
  "not worth the price. eggs in both the burrito and the bowl were flavorous rubber. so little sausage in the burrito that couldn't even get some in every bite. hasbrowns undercooked. everything was very bland. only positive were the tots were crispy in the bowl.",
  "in my personal opinion, a complete rip off for the price",
  "the burritos were not even what the description said. none of the promised ingredients. barely anything on them for the cost. it's like a $5 burrito for $14. i paid for extra sausage for my son and maybe got a link's worth cut up on top...for over $2 paid. way over priced and not what is advertised. ",
  "the philly was incredibly dry and was very small for the price, maybe 10' they also forgot the side of cheese sauce which probably would have helped. for the frings (half fries, half onion rings) im not convinced there were even onions in the onion rings it was all batter and the fries were undercooked and didnt have any salt or anything on them. ",
  "dry as heck not seasoned enough bland ",
  "more onions than meat. fixings fell out of bottom of bun when picked up. not worth the price.",
  "if i can rate a 0 i would don't order this bro ",
  "half of the order was wrong, and the food was terrible ",
  "i ordered a brownie and cheese sauce and didn't get either",
  "chicken was nasty and meal for the price was tiny!",
  "mostly egg. barely any sauce. bland sausage",
  "Only a few meatballs and little sauce. The second time was not as good as the first  ",
  "I wasn't given the correct meal. I order a $17.35 bowl not a 9.99 burrito.  ",
  "no buffalo sauce. definitely no double bacon. eggs didn't taste great.",
  "would never order again. the food tasted okay, but not worth the amount money at all. there was also a plastic bread tie in the burrito.",
  "disappointed. no cheese on the sandwich and i didn't opt to remove it. for the price, it really didn't seem worth it even if it had had the cheese. for a sandwich that is supposed to be covered with soup, or come with soup? the photos are misleading, it was very dry. probably will not order again considering the high price point.",
  "eggs were dry. eggs came with hot sauce, which was not in the description. very disappointing ",
  "small portion, bland, added bacon and barely had 5 bacon bit sized pieces",
  "paid $3.49 for orange juice have the tiniest cup in the world and with apple juice. i want my money back this is ridiculous.",
  "no marinara sauce on my chicken parm.  no drink either. , No marinara sauce.",
  "part of my order did not arrive and no one answered when i called for a refund on that part of the order. ",
];

const finalResult = ai.map((i, index) => {
  // console.log(i);
  return {
    prompt: reviews[index],
    completion: `${Object.entries(i).reduce((acc,[key, value]) => {
      const first_line = acc === "" ? "" : acc+',';
      return first_line+` ${key}: ${value}`;
    }, "")}`,
  };
});
console.log(finalResult[0]);

module.exports = { prompts: finalResult };
