const reviewsArray = [
  "cheesesteaks were good, but would have preferred plain bread instead of buttered bread. there was confusion with the order and computer system so took much longer than expected. ",
  "food overall was good, order was incorrect, but it was still very good. worth a try. ",
  "ordered the philly. sore said never received  order.  had to cme back to get. food was not great. this is not a grilled cheesesteak.the bread is toated  but the meat tasted like its in a heating station waiting in liquid until they are ready to assemble the sandwich. wont order again. ",
  "i didn't get my food i didn't even get the right restaurant ",
  "way to salty! waaayy to salty and the fries are plain. they tasted like mcdonald's fries with no salt left over night. ",
  "nothing was right and got no refund",
  "they sent me meat on bread. i ordered the cheesehead. if you are thinking of ordering here dont. 3rd time this week. if you walk in they are fine. you order on doordash forget it. your order will 100% wrong or not what you wanted. youve been warned ",
  "the sandwiches were average.  hardly any cheese and didn't taste fresh. ",
  "will not again order from here.  the phili was so salty i couldn't eat it.  i ordered double the meat, which the meat was so dried out.  there are better cheese steaks at gas stations.  i also ordered a coke, which ended up being a $3 can of coke.  an absolute waste of money!!!",
  "decent food, ignorantly expensive prices for the portions, will not return due to absurdly small servings",
  "order was wrong, $60 but $13 refund. garbage. save y money.",
  "burnt onions rings hair in sandwich ",
  "cheesehead came with no kraut, no onions, no whiz, pretty much nothing that was in the description. it did come with macaroni bites on the sandwhich. so kudos for trying",
  "Absolutely awful  ",
  "the meals were all sent vegetarian and what we chose was all supposed to have meat. not worthy the price paid and very disappointing  ",
  "not worth the price. eggs in both the burrito and the bowl were flavorous rubber. so little sausage in the burrito that couldn't even get some in every bite. hasbrowns undercooked. everything was very bland. only positive were the tots were crispy in the bowl.",
  "the burritos were not even what the description said. none of the promised ingredients. barely anything on them for the cost. it's like a $5 burrito for $14. i paid for extra sausage for my son and maybe got a link's worth cut up on top...for over $2 paid. way over priced and not what is advertised. ",
  'the philly was incredibly dry and was very small for the price, maybe 10" they also forgot the side of cheese sauce which probably would have helped. for the frings (half fries, half onion rings) im not convinced there were even onions in the onion rings it was all batter and the fries were undercooked and didnt have any salt or anything on them. ',
  "dry as heck not seasoned enough bland ",
  "more onions than meat. fixings fell out of bottom of bun when picked up. not worth the price.",
  "overall the sandwich was good. the only issue i had with the sandwich was the spring lettuce salad that was placed on top of it. it made the sandwich hard to eat . i suggest chopping up your greens a little.",
  "if i can rate a 0 i would don't order this bro ",
  "half of the order was wrong, and the food was terrible ",
  "i ordered a brownie and cheese sauce and didn't get either",
  "mostly egg. barely any sauce. bland sausage",
  "everything was cold :( we threw everything out wont be back again ",
  "ordered a combo with mac and cheese wedges didn't get them. also order took so long the bread was hard and cold. sad I was really looking forward to trying here. , was also missing a item ",
  "   mid",
  "I wasn't given the correct meal. I order a $17.35 bowl not a 9.99 burrito.  ",
  "no buffalo sauce. definitely no double bacon. eggs didn't taste great.",
  "would never order again. the food tasted okay, but not worth the amount money at all. there was also a plastic bread tie in the burrito.",
  "both burritos were supposed to have tots in them and we did not receive extra order of hash browns",
  "eggs were dry. eggs came with hot sauce, which was not in the description. very disappointing ",
  "small portion, bland, added bacon and barely had 5 bacon bit sized pieces",
  "paid $3.49 for orange juice have the tiniest cup in the world and with apple juice. i want my money back this is ridiculous.",
  "don't pay for anything extra like extra cheese or toppings cause they won't add it to your food.",
  "it was too salty never will order from this place again",
  "lowkey wasn't that good, made me wanna finish it as fast as i can .",
  "sent the wrong order and doordash now takes 24 hours to even fix it this is a complete joke\n",
  "hard and dry ",
  "frito bandito and cheesesteak daddy were terrible ",
  "food was horrible sandwitch was ashes and my fries was frozen ",
  "coulda been cheesier",
  "only giving one star because it wasn't an option for none..... steak extremely overcooked/burnt and dry.... tried to submit a complaint with no response and no one answers the phone number listed.... definitely won't order ever again",
  "only me combo does  not match description. small portion size no cheese i literally got the one with cheese and it has no cheese trying to get them to pick up i want refund",
  "i ordered the cheese head. in all fairness i did remove the onion and sourcraut, but what i received was barely a cheesesteak. of course it's not going to be overflowing like in the picture, but i at least expected it to be a decent amount of meat, even with the sourcraut removed. i wasn't expecting extra meat, but this sandwich is pathetic.",
  "the sandwich i received is not what i ordered, and on top of it the sandwich they did send me the meat is over cooked and dry. for the amount of time i had to wait past the estimated delivery time they could have gotten a one sandwich order correct. first time ordering, and is most likely the last unfortunately. ",
  "meat and buns were way overcooked.  entire meal was ruined, had to pick out what was edible off the top of the packs of meat.",
  "there was no meat in the burrito and the bagel was super super dry :/",
  "to cold.  , need to be freshly made",
  "not the right cheese steak  ",
  "   everything inside of the burrito tasted stale or rotten. i couldn't even finish the first bite",
  "burrito had no eggs, beef, or cheese. came with just tots and onions. was so disappointing after they took an extra 20 minutes beyond what was promised.",
  "the quality of food was awful. the burritos mostly consist of the wrap and not enough filling. the side of hashbrowns were burnt and tasted very off. would not recommend.  ",
  "first time trying this place and my burrito is missing half the ingredients lol..",
  "1st time trying this. they messed up the order and switched the burritos around.",
  "the sandwich was delicious, but the french fries were terribly under cooked. they were white and raw. for 4.99 for fries, they should at least be cooked properly. it ruined what would've been a perfect lunch",
  "they made the wrong sandwich no lettuce no tomatoe no extra cheese.. and wayyyyy to much garlic",
  "the sandwich had half meet for some reason. very disappointed and the fries were bot cooked properly either ",
  "hair in my food, too much onions",
  "the sheesehead had no cheese and extra things were added that were not listed as included toppings. what a shame",
  "ordered two wake n bake burritos, did not come with ground beef like listed, what's going on??",
  "food was dry over cook ",
  "Order never arrived! ",
  "i received the wrong item. the item i received was terrible. the side of cheese sauce was canned nacho cheese. i would not recommend.",
  "just not what i thought it would look like or taste like.",
  "i've ordered from here twice and and haven't gotten meat on my burrito either time. lot of potential if they can get their orders right",
  "way to expensive not even good ",
  "forgot my cream cheese and the oj spilled all over everything so can't even eat it. ",
  "items were not included in my order aaand items were not as described either. ordered a bagel with cream cheese and didn't get the cream cheese. ordered the basic b*tch bowl and received hash browns instead of tots. i was very disappointed. won't be coming back.",
];
