const { getOpenAIResponse } = require("../openai/fetchResponse");

const outlet_wise_deductions = [
  {
    restaurant_name: "Rockos Bar & Grill-Cheesesteak Daddy",
    listing_id: "P0011",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 17,
    order_processing_fee: 0,
    promo_spend_on_food: -52.98,
  },
  {
    restaurant_name: "Rockos Bar & Grill-Pop s Meatball Sandwich",
    listing_id: "P0012",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -6,
  },
  {
    restaurant_name: "Rockos Bar & Grill-Cheeky Bird",
    listing_id: "P0013",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -23.99,
  },
  {
    restaurant_name: "Bigtime Market-Cheesesteak Daddy",
    listing_id: "P0021",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 6.98,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "Bigtime Market-Pop s Meatball Sandwich",
    listing_id: "P0022",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "Bigtime Market-Cheeky Bird",
    listing_id: "P0023",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -6,
  },
  {
    restaurant_name: "Southgate Grill-Cheesesteak Daddy",
    listing_id: "P0041",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 2.1,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Southgate Grill-Pop s Meatball Sandwich",
    listing_id: "P0042",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Southgate Grill-Cheeky Bird",
    listing_id: "P0043",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Good Vibes Lounge-Cheesesteak Daddy",
    listing_id: "P0061",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Good Vibes Lounge-Pop s Meatball Sandwich",
    listing_id: "P0062",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Johnnys On The Lake -Cheesesteak Daddy",
    listing_id: "P0071",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 18.73,
    order_processing_fee: 0,
    promo_spend_on_food: -17,
  },
  {
    restaurant_name: "Johnnys On The Lake -Pop s Meatball Sandwich",
    listing_id: "P0072",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 6.3,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    listing_id: "P0081",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -6,
  },
  {
    restaurant_name:
      "Leos Coney Island-West Bloomfield-Pop s Meatball Sandwich",
    listing_id: "P0082",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "Leos Coney Island-West Bloomfield-Cheeky Bird",
    listing_id: "P0083",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 6,
    order_processing_fee: 0,
    promo_spend_on_food: -23,
  },
  {
    restaurant_name: "Fifth Avenue-Cheesesteak Daddy",
    listing_id: "P0091",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Fifth Avenue-Pop s Meatball Sandwich",
    listing_id: "P0092",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 5.1,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Detroit Grille House-Cheesesteak Daddy",
    listing_id: "P0101",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 11.12,
    order_processing_fee: 0,
    promo_spend_on_food: -44.79,
  },
  {
    restaurant_name: "Detroit Grille House-Pop s Meatball Sandwich",
    listing_id: "P0102",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Gator Jakes Bar & Grill-Cheesesteak Daddy",
    listing_id: "P0111",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 7.9,
    order_processing_fee: 0,
    promo_spend_on_food: -5,
  },
  {
    restaurant_name: "Gator Jakes Bar & Grill-Pop s Meatball Sandwich",
    listing_id: "P0112",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "Gator Jakes Bar & Grill-Cheeky Bird",
    listing_id: "P0113",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "The Beach Tiki Bar-Cheesesteak Daddy",
    listing_id: "P0131",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "The Beach Tiki Bar-Pop s Meatball Sandwich",
    listing_id: "P0132",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "US 12 Bar and Grill-Cheesesteak Daddy",
    listing_id: "P0141",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -21,
  },
  {
    restaurant_name: "US 12 Bar and Grill-Pop s Meatball Sandwich",
    listing_id: "P0142",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -12,
  },
  {
    restaurant_name: "US 12 Bar and Grill-Cheeky Bird",
    listing_id: "P0143",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -12,
  },
  {
    restaurant_name: "Leos Coney Island-Ann Arbor-Cheesesteak Daddy",
    listing_id: "P0151",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 13.7,
    order_processing_fee: 0,
    promo_spend_on_food: -9.23,
  },
  {
    restaurant_name: "Leos Coney Island-Ann Arbor-Pop s Meatball Sandwich",
    listing_id: "P0152",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 10.8,
    order_processing_fee: 0,
    promo_spend_on_food: -21.35,
  },
  {
    restaurant_name: "Leos Coney Island-Ann Arbor-Cheeky Bird",
    listing_id: "P0153",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 5.9,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-Bedhead Burritos and Bowls",
    listing_id: "P0161",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-Cheeky Bird",
    listing_id: "P0162",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-House of Parm",
    listing_id: "P0163",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-Pop s Meatball Sandwich",
    listing_id: "P0164",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name:
      "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    listing_id: "P0181",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -320,
  },
  {
    restaurant_name: "Red Olive Restaurant - Ferndale-House of Parm",
    listing_id: "P0182",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -9,
  },
  {
    restaurant_name: "Red Olive Restaurant - Ferndale-Pop s Meatball Sandwich",
    listing_id: "P0183",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -24,
  },
  {
    restaurant_name:
      "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    listing_id: "P0201",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 10.35,
    order_processing_fee: 0,
    promo_spend_on_food: -20.35,
  },
  {
    restaurant_name: "Leo s Coney Island - Miller Rd-House of Parm",
    listing_id: "P0202",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -14,
  },
  {
    restaurant_name: "Leo s Coney Island - Miller Rd-Pop s Meatball Sandwich",
    listing_id: "P0203",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Cameo Restaurant-Bedhead Burritos and Bowls",
    listing_id: "P0231",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 1.6,
    order_processing_fee: 0,
    promo_spend_on_food: -39,
  },
  {
    restaurant_name: "Cameo Restaurant-House of Parm",
    listing_id: "P0232",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Cameo Restaurant-Pop s Meatball Sandwich",
    listing_id: "P0233",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Classic Lanes-Cheeky Bird",
    listing_id: "P0241",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "Classic Lanes-Cheesesteak Daddy",
    listing_id: "P0242",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -25.99,
  },
  {
    restaurant_name: "Orange Tree Cafe Restaurant-Bedhead Burritos and Bowls",
    listing_id: "P0251",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -6,
  },
  {
    restaurant_name: "Orange Tree Cafe Restaurant-House of Parm",
    listing_id: "P0252",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -12,
  },
  {
    restaurant_name: "Orange Tree Cafe Restaurant-Pop s Meatball Sandwich",
    listing_id: "P0253",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -19.99,
  },
  {
    restaurant_name:
      "Leo s Coney Island - Ypsilanti-Bedhead Burritos and Bowls",
    listing_id: "P0261",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Leo s Coney Island - Ypsilanti-House of Parm",
    listing_id: "P0262",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name:
      "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    listing_id: "P0271",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -61,
  },
  {
    restaurant_name: "Red Olive Restaurant - Michigan-House of Parm",
    listing_id: "P0272",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -36.99,
  },
  {
    restaurant_name: "Red Olive Restaurant - Michigan-Pop s Meatball Sandwich",
    listing_id: "P0273",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -3,
  },
  {
    restaurant_name: "River Diner-Bedhead Burritos and Bowls",
    listing_id: "P0292",
    drive_charge: 0,
    marketing_fees: -23.69,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 6.8,
    order_processing_fee: 0,
    promo_spend_on_food: -57,
  },
  {
    restaurant_name: "River Diner-Pop s Meatball Sandwich",
    listing_id: "P0293",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -11,
  },
  {
    restaurant_name: "River Diner-House of Parm",
    listing_id: "P0291",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -56,
  },
  {
    restaurant_name: "Moe s Place-Cheesesteak Daddy",
    listing_id: "P0301",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 18.2,
    order_processing_fee: 0,
    promo_spend_on_food: 0,
  },
  {
    restaurant_name: "Moe s Place-Pop s Meatball Sandwich",
    listing_id: "P0302",
    drive_charge: 0,
    marketing_fees: 0,
    alcohol_flat_fee: 0,
    error_charges: 0,
    special_offer_delivery: 0,
    marketing_service_fee_adjustment: 0,
    bag_fee: 0,
    delivery_network_fee: 0,
    order_processing_fee: 0,
    promo_spend_on_food: -15,
  },
];

const outlet_wise_payable = [
  {
    restaurant_name:
      "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    sub_total: 2395.17,
    merchant_commission: -460.33,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -516.48,
    net_payout: 1089.46,
    tax_remitted_to_state: 139.75,
  },
  {
    restaurant_name: "River Diner-Bedhead Burritos and Bowls",
    sub_total: 925.31,
    merchant_commission: -95.98,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -155.47,
    net_payout: 634.93,
    tax_remitted_to_state: 0.77,
  },
  {
    restaurant_name: "Rockos Bar & Grill-Cheesesteak Daddy",
    sub_total: 677.04,
    merchant_commission: -102.42,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -8.65,
    net_payout: 472.79,
    tax_remitted_to_state: 33.52,
  },
  {
    restaurant_name: "River Diner-House of Parm",
    sub_total: 599.98,
    merchant_commission: -85,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -190.81,
    net_payout: 304.71,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name:
      "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    sub_total: 525.19,
    merchant_commission: -101.79,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -62.57,
    net_payout: 358.25,
    tax_remitted_to_state: 29.17,
  },
  {
    restaurant_name: "Cameo Restaurant-Bedhead Burritos and Bowls",
    sub_total: 408.79,
    merchant_commission: -81.16,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -277.51,
    net_payout: 3.02,
    tax_remitted_to_state: 23.16,
  },
  {
    restaurant_name: "Red Olive Restaurant - Michigan-House of Parm",
    sub_total: 395.83,
    merchant_commission: -78.77,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -306.56,
    net_payout: -3.76,
    tax_remitted_to_state: 22.86,
  },
  {
    restaurant_name: "Detroit Grille House-Cheesesteak Daddy",
    sub_total: 388.56,
    merchant_commission: -51.01,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -23.36,
    net_payout: 285.97,
    tax_remitted_to_state: 18.77,
  },
  {
    restaurant_name: "Red Olive Restaurant - Ferndale-Pop s Meatball Sandwich",
    sub_total: 341.73,
    merchant_commission: -69.92,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -125.5,
    net_payout: 170.3,
    tax_remitted_to_state: 19.97,
  },
  {
    restaurant_name: "Rockos Bar & Grill-Cheeky Bird",
    sub_total: 270.03,
    merchant_commission: -54.09,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -37.53,
    net_payout: 150.92,
    tax_remitted_to_state: 15.69,
  },
  {
    restaurant_name: "Red Olive Restaurant - Ferndale-House of Parm",
    sub_total: 236.77,
    merchant_commission: -50.1,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -168.68,
    net_payout: 4.51,
    tax_remitted_to_state: 14.22,
  },
  {
    restaurant_name: "Leos Coney Island-West Bloomfield-Cheeky Bird",
    sub_total: 235.86,
    merchant_commission: -33.61,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -62,
    net_payout: 120.61,
    tax_remitted_to_state: 11.24,
  },
  {
    restaurant_name: "US 12 Bar and Grill-Cheesesteak Daddy",
    sub_total: 224.25,
    merchant_commission: -44.72,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 158.53,
    tax_remitted_to_state: 13.28,
  },
  {
    restaurant_name: "Leo s Coney Island - Miller Rd-House of Parm",
    sub_total: 205.56,
    merchant_commission: -41.97,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -2,
    net_payout: 188.77,
    tax_remitted_to_state: 11.52,
  },
  {
    restaurant_name: "Orange Tree Cafe Restaurant-House of Parm",
    sub_total: 191.84,
    merchant_commission: -39.58,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -327.38,
    net_payout: -127.04,
    tax_remitted_to_state: 11.51,
  },
  {
    restaurant_name: "Moe s Place-Pop s Meatball Sandwich",
    sub_total: 152.36,
    merchant_commission: -30.24,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -110.07,
    net_payout: -8.95,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Johnnys On The Lake -Cheesesteak Daddy",
    sub_total: 151.61,
    merchant_commission: -14.46,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -8.02,
    net_payout: 70.54,
    tax_remitted_to_state: 7.06,
  },
  {
    restaurant_name:
      "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    sub_total: 151.26,
    merchant_commission: -15.35,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 120.12,
    tax_remitted_to_state: 6.33,
  },
  {
    restaurant_name: "US 12 Bar and Grill-Cheeky Bird",
    sub_total: 140.39,
    merchant_commission: -28.26,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -3.5,
    net_payout: 132.81,
    tax_remitted_to_state: 8.43,
  },
  {
    restaurant_name: "Classic Lanes-Cheesesteak Daddy",
    sub_total: 131.9,
    merchant_commission: -23.12,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -41.04,
    net_payout: 64.87,
    tax_remitted_to_state: 7.03,
  },
  {
    restaurant_name: "US 12 Bar and Grill-Pop s Meatball Sandwich",
    sub_total: 131.4,
    merchant_commission: -26.28,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 110.49,
    tax_remitted_to_state: 7.89,
  },
  {
    restaurant_name: "Johnnys On The Lake -Pop s Meatball Sandwich",
    sub_total: 125.89,
    merchant_commission: -13.18,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 94.17,
    tax_remitted_to_state: 4.5,
  },
  {
    restaurant_name: "Good Vibes Lounge-Cheesesteak Daddy",
    sub_total: 113.93,
    merchant_commission: -25.07,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -57.71,
    net_payout: 29.65,
    tax_remitted_to_state: 6.84,
  },
  {
    restaurant_name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    sub_total: 111.59,
    merchant_commission: -23.23,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -7.87,
    net_payout: 101.95,
    tax_remitted_to_state: 6.7,
  },
  {
    restaurant_name: "Gator Jakes Bar & Grill-Cheesesteak Daddy",
    sub_total: 94.16,
    merchant_commission: -0.17,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -8.21,
    net_payout: 84.76,
    tax_remitted_to_state: 1.81,
  },
  {
    restaurant_name: "River Diner-Pop s Meatball Sandwich",
    sub_total: 90.93,
    merchant_commission: -7.91,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -36.14,
    net_payout: 38.8,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Moe s Place-Cheesesteak Daddy",
    sub_total: 90.92,
    merchant_commission: 11.65,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 61.07,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Orange Tree Cafe Restaurant-Pop s Meatball Sandwich",
    sub_total: 89.88,
    merchant_commission: -15.38,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -38.34,
    net_payout: 24.53,
    tax_remitted_to_state: 5.4,
  },
  {
    restaurant_name: "Leos Coney Island-Ann Arbor-Pop s Meatball Sandwich",
    sub_total: 77.93,
    merchant_commission: -4,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -4.42,
    net_payout: 39.2,
    tax_remitted_to_state: 2.94,
  },
  {
    restaurant_name: "Orange Tree Cafe Restaurant-Bedhead Burritos and Bowls",
    sub_total: 76.87,
    merchant_commission: -15.59,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -86.32,
    net_payout: 10.2,
    tax_remitted_to_state: 4.19,
  },
  {
    restaurant_name: "Classic Lanes-Cheeky Bird",
    sub_total: 73.89,
    merchant_commission: -15.59,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 75.72,
    tax_remitted_to_state: 4.43,
  },
  {
    restaurant_name: "Leos Coney Island-Ann Arbor-Cheesesteak Daddy",
    sub_total: 72.92,
    merchant_commission: 3.16,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -12.1,
    net_payout: 35.38,
    tax_remitted_to_state: 1.2,
  },
  {
    restaurant_name: "Bigtime Market-Cheeky Bird",
    sub_total: 65.45,
    merchant_commission: -13.09,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 58.35,
    tax_remitted_to_state: 3.93,
  },
  {
    restaurant_name: "Fifth Avenue-Pop s Meatball Sandwich",
    sub_total: 58.95,
    merchant_commission: -1.1,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -22.6,
    net_payout: 22.23,
    tax_remitted_to_state: 1.38,
  },
  {
    restaurant_name: "Red Olive Restaurant - Michigan-Pop s Meatball Sandwich",
    sub_total: 58.95,
    merchant_commission: -12.31,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 68.48,
    tax_remitted_to_state: 3.54,
  },
  {
    restaurant_name: "Leo s Coney Island - Miller Rd-Pop s Meatball Sandwich",
    sub_total: 48.46,
    merchant_commission: -10.67,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 44.61,
    tax_remitted_to_state: 2.91,
  },
  {
    restaurant_name: "Rockos Bar & Grill-Pop s Meatball Sandwich",
    sub_total: 38.96,
    merchant_commission: -7.26,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -6.14,
    net_payout: 19.56,
    tax_remitted_to_state: 2.34,
  },
  {
    restaurant_name: "Bigtime Market-Cheesesteak Daddy",
    sub_total: 38.96,
    merchant_commission: -4.63,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 27.99,
    tax_remitted_to_state: 2.34,
  },
  {
    restaurant_name: "Leos Coney Island-Ann Arbor-Cheeky Bird",
    sub_total: 36.97,
    merchant_commission: -3.19,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -13,
    net_payout: 15.42,
    tax_remitted_to_state: 1.32,
  },
  {
    restaurant_name: "Gator Jakes Bar & Grill-Pop s Meatball Sandwich",
    sub_total: 26.96,
    merchant_commission: -5.27,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 28.13,
    tax_remitted_to_state: 1.62,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-Pop s Meatball Sandwich",
    sub_total: 24.54,
    merchant_commission: -4.51,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -4.31,
    net_payout: 12.72,
    tax_remitted_to_state: 0.36,
  },
  {
    restaurant_name:
      "Leos Coney Island-West Bloomfield-Pop s Meatball Sandwich",
    sub_total: 23.99,
    merchant_commission: -4.62,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 30.44,
    tax_remitted_to_state: 1.44,
  },
  {
    restaurant_name: "Bigtime Market-Pop s Meatball Sandwich",
    sub_total: 21.98,
    merchant_commission: -4.18,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 18.98,
    tax_remitted_to_state: 1.32,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-Cheeky Bird",
    sub_total: 20.98,
    merchant_commission: -4.62,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 20.98,
    tax_remitted_to_state: 1.26,
  },
  {
    restaurant_name: "The Beach Tiki Bar-Cheesesteak Daddy",
    sub_total: 20.97,
    merchant_commission: -3.95,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 22.37,
    tax_remitted_to_state: 1.26,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-House of Parm",
    sub_total: 19.99,
    merchant_commission: -3.74,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 13.25,
    tax_remitted_to_state: 1.2,
  },
  {
    restaurant_name: "Gator Jakes Bar & Grill-Cheeky Bird",
    sub_total: 14.99,
    merchant_commission: -3.3,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -48.5,
    net_payout: -25.27,
    tax_remitted_to_state: 0.9,
  },
  {
    restaurant_name: "Southgate Grill-Cheesesteak Daddy",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 13.95,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Southgate Grill-Pop s Meatball Sandwich",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Southgate Grill-Cheeky Bird",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -2.24,
    net_payout: -3.24,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Good Vibes Lounge-Pop s Meatball Sandwich",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Fifth Avenue-Cheesesteak Daddy",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Detroit Grille House-Pop s Meatball Sandwich",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "The Beach Tiki Bar-Pop s Meatball Sandwich",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: -6.72,
    net_payout: 1.41,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Leo s Coney Island - Clio-Bedhead Burritos and Bowls",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 12.18,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Cameo Restaurant-House of Parm",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Cameo Restaurant-Pop s Meatball Sandwich",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name:
      "Leo s Coney Island - Ypsilanti-Bedhead Burritos and Bowls",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
  {
    restaurant_name: "Leo s Coney Island - Ypsilanti-House of Parm",
    sub_total: 0,
    merchant_commission: 0,
    tips: 0,
    adjustments: 0,
    miscellaneous_payments: 0,
    net_payout: 0,
    tax_remitted_to_state: 0,
  },
];
const overall_finance = {
  current_period: [{ start_date: "2023-03-18", end_date: "2023-04-17" }],
  prev__period: [{ start_date: "2023-02-15", end_date: "2023-03-18" }],
  platform_commission: -1719.91,
  total_deductions: -3766.35,
  net_payout: {
    curr_net_payout: 5299.82,
    prev_net_payout: 5674.28,
    percentage_difference: -6.6,
  },
  tax_remitted_to_state: 467.3,
  order_value: 10420.84,
};

const PROMPT_DEDUCTION = `Consider yourself as statistical analyst expert, you have been given outlet wise deduction data, try to find out the insights from the data
`;
const PROMPT_PAYABLE = `Consider yourself as statistical analyst expert, you have been given outlet wise payable data, try to find out the insights from the data and the response should be of 50 words or less
`;

const PROMPT_FINANCE = `Consider yourself as statistical analyst expert, you have been given overall finance data, try to find out the insights from the data(comparison and some percentage difference, etc) and the response should be of 50 words or less`

// -----------------------------------------------------------

module.exports = {
  getFinanceInsights: async () => {
    // payload is large
    // const data_one = await getOpenAIResponse(
    //   outlet_wise_deductions,
    //   PROMPT_DEDUCTION,
    //   "finance outlet wise deductions"
    // );
    const data_two = await getOpenAIResponse(
      outlet_wise_payable,
      PROMPT_PAYABLE,
      "finance outlet wise payable"
    );
    const data_three = await getOpenAIResponse(
      overall_finance,
      PROMPT_FINANCE,
      "finance overall details"
    );



    if (!data_two.status || !data_three.status) {
      return {
        status: false,
        error: data.error,
      };
    }
    return {
      status: true,
      data: {
        // deductions: data_one.response,
        payable: data_two.response,
        overall: data_three.response,
      },
    };
  },
};
