const reviews = [
  {
    name: "Rockos Bar & Grill-Cheesesteak Daddy",
    feedback: "unbelievable cheesesteak! wowowow!!",
    order_id: "195e8870",
    rating: 5,
    outlet: "P0011",
    channel: "DOORDASH",
  },
  {
    name: "Overtyme Bar & Grill-Cheesesteak Daddy",
    feedback:
      "yum! the philly was so tasty! great portion. hot and fresh! highly recommend trying this place. i loved it",
    order_id: "a3c02eb7",
    rating: 5,
    outlet: "P0031",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "amazing! the philly was fantastic! i'm from philly and this stacks up against the philly's i was raised with. will definitely be reordering. ",
    order_id: "06c6d8ad",
    rating: 5,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback: "delicious cheesesteak. seriously good stuff!",
    order_id: "af05318f",
    rating: 5,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "food overall was good, order was incorrect, but it was still very good. worth a try. ",
    order_id: "b658bc76",
    rating: 3,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "ordered the philly. sore said never received  order.  had to cme back to get. food was not great. this is not a grilled cheesesteak.the bread is toated  but the meat tasted like its in a heating station waiting in liquid until they are ready to assemble the sandwich. wont order again. ",
    order_id: "12dbe24c",
    rating: 3,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "this is my second time ordering from here and it is always perfection. fast and hot! my new favorite cheesesteak place!  ",
    order_id: "a42cf953",
    rating: 5,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback: "i didn't get my food i didn't even get the right restaurant ",
    order_id: "073ce65d",
    rating: 1,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Bigtime Market-Cheesesteak Daddy",
    feedback: "it was great",
    order_id: "02110e53",
    rating: 5,
    outlet: "P0021",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback:
      "whoa daddy! i'm officially addicted! best sandwiches in town. this place slaps so hard!",
    order_id: "4ad9c8e1",
    rating: 5,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback:
      "wow! the philly was outstanding! hot, fresh, super fast and such a nice size sandwich! can't wait to try this place again. highly recommend trying cheesesteak daddy!",
    order_id: "dd5532f6",
    rating: 5,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "the bomb! order now you won't regret it",
    order_id: "6ee2530c",
    rating: 5,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback:
      "this place is so fire!!! my new go-to sandwich spot. food is super fresh and i love the variety of options! great experience ",
    order_id: "5a24c85f",
    rating: 5,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback:
      "way to salty! waaayy to salty and the fries are plain. they tasted like mcdonald's fries with no salt left over night. ",
    order_id: "dcebb25f",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "nothing was right and got no refund",
    order_id: "ff1f337a",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Good Vibes Lounge-Cheesesteak Daddy",
    feedback:
      "food was soo good . fries were hot and fresh . ordered because of the reviews and will definitely be ordering again ! the bread was so good . they did forget that i paid to add cheez wiz but they gave me a free cookie . 10/10!",
    order_id: "3842943c",
    rating: 5,
    outlet: "P0061",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "cheesesteaks were good, but would have preferred plain bread instead of buttered bread. there was confusion with the order and computer system so took much longer than expected. ",
    order_id: "1bb1dc47",
    rating: 3,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback: "the philly po' boy is wonderfully delicious. always fresh ",
    order_id: "53295462",
    rating: 5,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Cheesesteak Daddy",
    feedback:
      "it was the best cheesesteak i've had in years. tasted like the quality tubby's used to have. and finding out it was local instead of a chain was a bonus.",
    order_id: "df8ac527",
    rating: 5,
    outlet: "P0071",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Cheesesteak Daddy",
    feedback: "both of our sandwiches were really great. delivery was fast",
    order_id: "5ea53580",
    rating: 5,
    outlet: "P0071",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Cheesesteak Daddy",
    feedback: "friggin yummy af!",
    order_id: "08c97f81",
    rating: 5,
    outlet: "P0071",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback: "wow! so good!",
    order_id: "fe0c795d",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "the the philly  was tasty and the cheese sauce is magical. i will be back daddy",
    order_id: "5233bed8",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "they sent me meat on bread. i ordered the cheesehead. if you are thinking of ordering here dont. 3rd time this week. if you walk in they are fine. you order on doordash forget it. your order will 100% wrong or not what you wanted. youve been warned ",
    order_id: "fe714c4d",
    rating: 1,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Cheesesteak Daddy",
    feedback: "woah daddy!! super good. loved that cheesesteak!",
    order_id: "4de6fc79",
    rating: 5,
    outlet: "P0101",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Cheesesteak Daddy",
    feedback:
      "the sandwiches were average.  hardly any cheese and didn't taste fresh. ",
    order_id: "238a7a4b",
    rating: 3,
    outlet: "P0101",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Cheesesteak Daddy",
    feedback:
      "will not again order from here.  the phili was so salty i couldn't eat it.  i ordered double the meat, which the meat was so dried out.  there are better cheese steaks at gas stations.  i also ordered a coke, which ended up being a $3 can of coke.  an absolute waste of money!!!",
    order_id: "fb34f173",
    rating: 1,
    outlet: "P0101",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "fantastic philly cheesesteak! bread was good and delivered still hot and toasty, steak was juicy and good portion. will be ordering again!",
    order_id: "1b49c71c",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Cheesesteak Daddy",
    feedback: "the sub was great! ",
    order_id: "b260755c",
    rating: 5,
    outlet: "P0121",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Cheesesteak Daddy",
    feedback:
      "tried this new local business out and i'msure glad i did this is one of my new favorites! great food!  ",
    order_id: "0b6edb17",
    rating: 5,
    outlet: "P0121",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Cheesesteak Daddy",
    feedback: "mmmmm cheesesteak daddy yessss",
    order_id: "9e88bb28",
    rating: 5,
    outlet: "P0121",
    channel: "DOORDASH",
  },
  {
    name: "The Beach Tiki Bar-Cheesesteak Daddy",
    feedback: "wow that pizza steak was fire!!!",
    order_id: "6810bad0",
    rating: 5,
    outlet: "P0131",
    channel: "DOORDASH",
  },
  {
    name: "The Beach Tiki Bar-Cheesesteak Daddy",
    feedback:
      "the frito bandito was exceptional! highly recommend trying these guys. will be reordering this weekend!",
    order_id: "d2b9a4bb",
    rating: 5,
    outlet: "P0131",
    channel: "DOORDASH",
  },
  {
    name: "The Beach Tiki Bar-Cheesesteak Daddy",
    feedback: "this place is da bomb! the frito bandito was amazingggg",
    order_id: "cd76b473",
    rating: 5,
    outlet: "P0131",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Cheesesteak Daddy",
    feedback:
      "decent food, ignorantly expensive prices for the portions, will not return due to absurdly small servings",
    order_id: "9eabafe7",
    rating: 3,
    outlet: "P0141",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Cheesesteak Daddy",
    feedback: "sooo yummy! try this place",
    order_id: "e49b0cdd",
    rating: 5,
    outlet: "P0141",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Cheesesteak Daddy",
    feedback:
      "the cheesesteak was fabulous, the meat was really tender. the poboy was delicious.",
    order_id: "56101cdc",
    rating: 5,
    outlet: "P0141",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Cheesesteak Daddy",
    feedback: "order was wrong, $60 but $13 refund. garbage. save y money.",
    order_id: "c7975b71",
    rating: 1,
    outlet: "P0141",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Pop s Meatball Sandwich",
    feedback:
      "holy meatball! the mac n' the mac n' meatball was the tastiest sandwich i have ever eaten!!! super fresh and huge portion! love this place.",
    order_id: "ce40328f",
    rating: 5,
    outlet: "P0042",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Pop s Meatball Sandwich",
    feedback: "i got a marinara meatball sub",
    order_id: "e7416181",
    rating: 1,
    outlet: "P0052",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Pop s Meatball Sandwich",
    feedback: "loved it!! perfect meatball sandwich! ",
    order_id: "bdae497d",
    rating: 5,
    outlet: "P0072",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Pop s Meatball Sandwich",
    feedback:
      "forever, my favorite food was french onion soup... then i met pop and tried the the frenchy meatball. oh my goodness, my life has changed! the frenchy meatball is my new favorite food!! phenomenal sandwich. you have to try this place! thanks pop!!!",
    order_id: "52feb874",
    rating: 5,
    outlet: "P0082",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Pop s Meatball Sandwich",
    feedback: "best sandwich i had in a long time ",
    order_id: "edbbd395",
    rating: 5,
    outlet: "P0142",
    channel: "DOORDASH",
  },
  {
    name: "Rockos Bar & Grill-Cheesesteak Daddy",
    feedback:
      "phenomenal! super tasty! loved the frito  bandito. highly recommend. this place is awesome!!",
    order_id: "a035f26f",
    rating: 5,
    outlet: "P0011",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Cheesesteak Daddy",
    feedback:
      "this place is so good, i love it! order it all the time and it's always good ",
    order_id: "ce42418e",
    rating: 5,
    outlet: "P0071",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Cheesesteak Daddy",
    feedback: "really dang good! love the pizza steak and the philly",
    order_id: "538b1d40",
    rating: 5,
    outlet: "P0141",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "burnt onions rings hair in sandwich ",
    order_id: "7f991bb0",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Gator Jakes Bar & Grill-Cheesesteak Daddy",
    feedback:
      "it's 14/10 everything about this establishment￼ wakes up in the morning￼ and just excretes excellence￼",
    order_id: "05b5b99b",
    rating: 5,
    outlet: "P0111",
    channel: "DOORDASH",
  },
  {
    name: "Rockos Bar & Grill-Cheesesteak Daddy",
    feedback:
      " the pizza steak was real fire! the philly was unreal! portions were great and food tasted awesome!!",
    order_id: "eb1de300",
    rating: 5,
    outlet: "P0011",
    channel: "DOORDASH",
  },
  {
    name: "Rockos Bar & Grill-Cheesesteak Daddy",
    feedback:
      "the frito bandito was exceptional. can't wait to order this place again. highly recommend.",
    order_id: "01776fad",
    rating: 5,
    outlet: "P0011",
    channel: "DOORDASH",
  },
  {
    name: "Rockos Bar & Grill-Cheesesteak Daddy",
    feedback:
      "don't pay for anything extra like extra cheese or toppings cause they won't add it to your food.",
    order_id: "8d3f4ee4",
    rating: 1,
    outlet: "P0011",
    channel: "DOORDASH",
  },
  {
    name: "Overtyme Bar & Grill-Cheesesteak Daddy",
    feedback: "one of the best cheese steaks i have had in the area",
    order_id: "920c856c",
    rating: 5,
    outlet: "P0031",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "the the pizza steak was so fire!!! try this immediately. you won't regret it. ",
    order_id: "eb0805b2",
    rating: 5,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "it was too salty never will order from this place again",
    order_id: "62fc4b37",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback:
      "lowkey wasn't that good, made me wanna finish it as fast as i can .",
    order_id: "aa759e09",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "still fresh and the fries also! will order again",
    order_id: "ef92bdf1",
    rating: 5,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "must try! phenomenal sandwiches! will order again!!",
    order_id: "f0278042",
    rating: 5,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Cheesesteak Daddy",
    feedback:
      "sent the wrong order and doordash now takes 24 hours to even fix it this is a complete joke\n",
    order_id: "5b494f76",
    rating: 1,
    outlet: "P0071",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback: "hard and dry ",
    order_id: "8f4c94d2",
    rating: 1,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback: "yummy yummy! thank you!!",
    order_id: "090bc813",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "both of our sandwiches were really good. i was really impressed. will order again",
    order_id: "8807fe91",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback: "frito bandito and cheesesteak daddy were terrible ",
    order_id: "48a2fe7c",
    rating: 1,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Good Vibes Lounge-Cheesesteak Daddy",
    feedback: "food was horrible sandwitch was ashes and my fries was frozen ",
    order_id: "129b0628",
    rating: 1,
    outlet: "P0061",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Cheesesteak Daddy",
    feedback: "the philly po' boy and the pizza steak were both excellent",
    order_id: "45385062",
    rating: 5,
    outlet: "P0101",
    channel: "DOORDASH",
  },
  {
    name: "Gator Jakes Bar & Grill-Cheesesteak Daddy",
    feedback: "coulda been cheesier",
    order_id: "ffbec211",
    rating: 3,
    outlet: "P0111",
    channel: "DOORDASH",
  },
  {
    name: "Gator Jakes Bar & Grill-Cheesesteak Daddy",
    feedback:
      "they put a cookie in the bag with the order :). haven't tasted the food yet but i like it already ",
    order_id: "2b16590d",
    rating: 5,
    outlet: "P0111",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Cheesesteak Daddy",
    feedback: "best food i've had in a very long time. love this place!!",
    order_id: "fd14d4bb",
    rating: 5,
    outlet: "P0121",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Cheesesteak Daddy",
    feedback:
      "hands down best cheesesteak i've ever had. i've been to philly and this blows it out of the water. better than lefty's. better than penn station. better than tubbys. if you are ever considering getting a cheesteak it would be fiscally irresponsible not to get this one. ",
    order_id: "0aae03ba",
    rating: 5,
    outlet: "P0121",
    channel: "DOORDASH",
  },
  {
    name: "The Beach Tiki Bar-Cheesesteak Daddy",
    feedback:
      "loved that you can create your own cheesesteak with the byo byo cheesesteak! it was perfect. made exactly the way i wanted it and straight fireeee! love this place!!",
    order_id: "ceb286b4",
    rating: 5,
    outlet: "P0131",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Cheesesteak Daddy",
    feedback:
      "only giving one star because it wasn't an option for none..... steak extremely overcooked/burnt and dry.... tried to submit a complaint with no response and no one answers the phone number listed.... definitely won't order ever again",
    order_id: "f67f1f75",
    rating: 1,
    outlet: "P0141",
    channel: "DOORDASH",
  },
  {
    name: "Rockos Bar & Grill-Pop s Meatball Sandwich",
    feedback: "delicious! loved it! ",
    order_id: "ea6217f3",
    rating: 5,
    outlet: "P0012",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Pop s Meatball Sandwich",
    feedback: "one of the best meatball subs i've ever had!!",
    order_id: "2dd445cc",
    rating: 5,
    outlet: "P0042",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Pop s Meatball Sandwich",
    feedback:
      "the absolutely largest, thickest onion rings i've ever seen and they were delicious! ",
    order_id: "81a7a8b5",
    rating: 5,
    outlet: "P0102",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Pop s Meatball Sandwich",
    feedback:
      "ordered the mac and meatball. didn't receive any mac and cheese wedges, but the sandwich was alright. sauce has a nice spicy kick to it ",
    order_id: "e35e8b76",
    rating: 4,
    outlet: "P0072",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Pop s Meatball Sandwich",
    feedback: "this was awesome - definitely recommend",
    order_id: "20376253",
    rating: 5,
    outlet: "P0122",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Pop s Meatball Sandwich",
    feedback: "delicious!!!",
    order_id: "4be1e43b",
    rating: 5,
    outlet: "P0122",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheeky Bird",
    feedback:
      "the og was so tasty! fast, fresh, hot and delicious. highly recommend!",
    order_id: "4495471d",
    rating: 5,
    outlet: "P0043",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheeky Bird",
    feedback:
      "the deluxe clucks was fantastic! try this place asap! it's sooo fire",
    order_id: "8ef49a0f",
    rating: 5,
    outlet: "P0053",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback: "fast and always fresh! man, i love this place!!! never fails. ",
    order_id: "29515722",
    rating: 5,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheeky Bird",
    feedback: "didn't get the right order",
    order_id: "6878901d",
    rating: 1,
    outlet: "P0053",
    channel: "DOORDASH",
  },
  {
    name: "Good Vibes Lounge-Cheesesteak Daddy",
    feedback:
      "only me combo does  not match description. small portion size no cheese i literally got the one with cheese and it has no cheese trying to get them to pick up i want refund",
    order_id: "ea24fdce",
    rating: 1,
    outlet: "P0061",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Cheesesteak Daddy",
    feedback:
      "i ordered the cheese head. in all fairness i did remove the onion and sourcraut, but what i received was barely a cheesesteak. of course it's not going to be overflowing like in the picture, but i at least expected it to be a decent amount of meat, even with the sourcraut removed. i wasn't expecting extra meat, but this sandwich is pathetic.",
    order_id: "3d93cd37",
    rating: 2,
    outlet: "P0141",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Ann Arbor-Cheesesteak Daddy",
    feedback: "that was a dang good philly cheesesteak",
    order_id: "f0e5aa61",
    rating: 5,
    outlet: "P0151",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Ann Arbor-Cheesesteak Daddy",
    feedback: "yassssss girlll this place is my fav",
    order_id: "70f9144e",
    rating: 5,
    outlet: "P0151",
    channel: "DOORDASH",
  },
  {
    name: "Overtyme Bar & Grill-Cheesesteak Daddy",
    feedback: "them were some tasty cheesesteaks ty!!",
    order_id: "1e6e604b",
    rating: 5,
    outlet: "P0031",
    channel: "DOORDASH",
  },
  {
    name: "Bigtime Market-Cheesesteak Daddy",
    feedback:
      "the sandwich i received is not what i ordered, and on top of it the sandwich they did send me the meat is over cooked and dry. for the amount of time i had to wait past the estimated delivery time they could have gotten a one sandwich order correct. first time ordering, and is most likely the last unfortunately. ",
    order_id: "0ef3e415",
    rating: 1,
    outlet: "P0021",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "meat and buns were way overcooked.  entire meal was ruined, had to pick out what was edible off the top of the packs of meat.",
    order_id: "5858dec5",
    rating: 1,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback: "very good pasta, excellent flavor! tasty and big portion ",
    order_id: "070894ce",
    rating: 5,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      "the cavatappi with creamy pesto was delicious! flavorful and all i can say is sheeeeeesh, you gotta try this place. nuff said. its flame sauce f'real f'real.",
    order_id: "8cbfbc86",
    rating: 5,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      "honestly really good, was surprised because i'm picky with my pasta but it was actually great. give this pasta a try!",
    order_id: "3a9c8ebe",
    rating: 5,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-House of Parm",
    feedback:
      'it would be nice if we knew we were ordering from leos ciney island instead of "house of parm"....',
    order_id: "cf1f83c7",
    rating: 3,
    outlet: "P0202",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-House of Parm",
    feedback:
      "great pasta option - huge portion! i ordered for lunch and have enough leftover for dinner",
    order_id: "c4b9b4a6",
    rating: 5,
    outlet: "P0202",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Pop s Meatball Sandwich",
    feedback:
      "the pop's original was so fire! my new go-to sandwich! thanks pop!!",
    order_id: "14269904",
    rating: 5,
    outlet: "P0203",
    channel: "DOORDASH",
  },
  {
    name: "Classic Lanes-Cheesesteak Daddy",
    feedback:
      "po boy and philly were both great. juicy steak, quality too, nice portions",
    order_id: "def994d8",
    rating: 5,
    outlet: "P0242",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "there was no meat in the burrito and the bagel was super super dry :/",
    order_id: "ecf77d99",
    rating: 1,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-House of Parm",
    feedback: "pesto pasta was really good!!!!!!!!",
    order_id: "cbdd8ff9",
    rating: 5,
    outlet: "P0272",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Pop s Meatball Sandwich",
    feedback: "i upgraded to Onion rings and still got fries ",
    order_id: "cf9d7840",
    rating: 2,
    outlet: "P0052",
    channel: "UBEREATS",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "to cold.  , need to be freshly made",
    order_id: "15cf3222",
    rating: 3,
    outlet: "P0051",
    channel: "UBEREATS",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback: "not the right cheese steak  ",
    order_id: "98f6917b",
    rating: 3,
    outlet: "P0041",
    channel: "UBEREATS",
  },
  {
    name: "Gator Jakes Bar & Grill-Cheesesteak Daddy",
    feedback: "   mid",
    order_id: "a97fe441",
    rating: 1,
    outlet: "P0111",
    channel: "UBEREATS",
  },
  {
    name: "Rockos Bar & Grill-Cheesesteak Daddy",
    feedback:
      "   everything inside of the burrito tasted stale or rotten. i couldn't even finish the first bite",
    order_id: "306c60d6",
    rating: 2,
    outlet: "P0011",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Pop s Meatball Sandwich",
    feedback:
      "food cane cold and they did not even care to remake and sent hour hold??!! ",
    order_id: "f76b2f79",
    rating: 1,
    outlet: "P0183",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback: "   the promotion didnt work ",
    order_id: "d3485d20",
    rating: 1,
    outlet: "P0182",
    channel: "UBEREATS",
  },
  {
    name: "Orange Tree Cafe Restaurant-Bedhead Burritos and Bowls",
    feedback:
      "very very good! dont sleep on this place, its my new spot! absolute fire!",
    order_id: "3b383203",
    rating: 5,
    outlet: "P0251",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "burrito had no eggs, beef, or cheese. came with just tots and onions. was so disappointing after they took an extra 20 minutes beyond what was promised.",
    order_id: "f84f8f24",
    rating: 1,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-House of Parm",
    feedback: "actually leo's, overcooked, appetizer sized 20$ diner bull****",
    order_id: "0e75e046",
    rating: 1,
    outlet: "P0202",
    channel: "DOORDASH",
  },
  {
    name: "Gator Jakes Bar & Grill-Pop s Meatball Sandwich",
    feedback:
      "Driver was great...order was delivered very quickly and the driver was very courteous....5 stars for the delivery driver \n\nMeatball sub was ridiculously overpriced, 4 small meatballs that only partially filled the bun...Sandwich was delivered very quickly and yet it was somehow only slightly warm.   The garlic bread was slightly soggy and the cheese was only partially melted.  15 dollars for a 4 small meatballs sub...I could have gotten 2 meatball subs from Subway for less money and gotten 3-4x the food and probably a better quality.  1 star for the food...it was decent but it wasn't anywhere near worth the cost.",
    order_id: "249d1a60",
    rating: 3,
    outlet: "P0112",
    channel: "GRUBHUB",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback: "it was just okay. not offensive, not great",
    order_id: "40228f99",
    rating: 3,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Cameo Restaurant-House of Parm",
    feedback: "wasn't a fan. ",
    order_id: "e260c380",
    rating: 2,
    outlet: "P0232",
    channel: "DOORDASH",
  },
  {
    name: "Cameo Restaurant-House of Parm",
    feedback: "mid",
    order_id: "1ce46f01",
    rating: 3,
    outlet: "P0232",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "the bacon cheeseburger philly was my oh my tasty! the fiesta philly slaps! holy cheesteak, you have to try this place!!",
    order_id: "b3c5bdc5",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "the quality of food was awful. the burritos mostly consist of the wrap and not enough filling. the side of hashbrowns were burnt and tasted very off. would not recommend.  ",
    order_id: "39a5ba9c",
    rating: 1,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Orange Tree Cafe Restaurant-Bedhead Burritos and Bowls",
    feedback:
      "first time trying this place and my burrito is missing half the ingredients lol..",
    order_id: "a0f74fc8",
    rating: 1,
    outlet: "P0251",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-House of Parm",
    feedback:
      "The pasta taste like it was very undercooked and it was very chalky and pasty. And for $18. I expected a little bit more on the portion. ",
    order_id: "0f46d3ce",
    rating: 1,
    outlet: "P0272",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      "This is not really chicken marsala. It's a mushrooms sauce on fettuccine, with a salty, dry, grilled chicken breast on the top.  I was duped. Now you know.",
    order_id: "06877d95",
    rating: 1,
    outlet: "P0182",
    channel: "GRUBHUB",
  },
  {
    name: "Leo s Coney Island - Miller Rd-House of Parm",
    feedback:
      "It was exactly as I expected it and it tasted better than I thought it would. Would order again ",
    order_id: "b3ea8801",
    rating: 5,
    outlet: "P0202",
    channel: "GRUBHUB",
  },
  {
    name: "Leo s Coney Island - Clio-Bedhead Burritos and Bowls",
    feedback:
      "1st time trying this. they messed up the order and switched the burritos around.",
    order_id: "596c28cf",
    rating: 1,
    outlet: "P0161",
    channel: "DOORDASH",
  },
  {
    name: "Overtyme Bar & Grill-Cheesesteak Daddy",
    feedback: "the mac and cheese wedges are awesome!",
    order_id: "de982f47",
    rating: 5,
    outlet: "P0031",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      "the sandwich was delicious, but the french fries were terribly under cooked. they were white and raw. for 4.99 for fries, they should at least be cooked properly. it ruined what would've been a perfect lunch",
    order_id: "3ee5b07b",
    rating: 3,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "the philly was exceptional. hot, fresh, fast delivery. great experience",
    order_id: "e0bcbed2",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "CK Diggs-Cheesesteak Daddy",
    feedback:
      "it was my first time trying this place today... mannnnn! they definitely do not disappoint with the food! quality flavor, amazing prices as well. i would give this place a go for sure! support the local businesses so they can keep growing! i love this place! ",
    order_id: "4a40eaf7",
    rating: 5,
    outlet: "P0121",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Pop s Meatball Sandwich",
    feedback:
      "tried the the frenchy meatball and the mac n' the mac n' meatball sandwiches. outstanding!!! so fresh. super fast delivery! absolutely loved the experience. thank you pop!!",
    order_id: "02743f0e",
    rating: 5,
    outlet: "P0082",
    channel: "DOORDASH",
  },
  {
    name: "The Beach Tiki Bar-Pop s Meatball Sandwich",
    feedback:
      "wants expecting it to be so spicy. it was good but to spicy for me ",
    order_id: "9ca9f6ff",
    rating: 3,
    outlet: "P0132",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheeky Bird",
    feedback: "chicken finger hoagie sandwiches - nothing not to like! ",
    order_id: "2dded02b",
    rating: 5,
    outlet: "P0083",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Cheesesteak Daddy",
    feedback:
      "they made the wrong sandwich no lettuce no tomatoe no extra cheese.. and wayyyyy to much garlic",
    order_id: "681e1b4f",
    rating: 1,
    outlet: "P0101",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Pop s Meatball Sandwich",
    feedback:
      "ordered a pop's original and it should have had tomato sauce and provolone cheese.  sub came plain with some kind of yellow cheese.  not what i ordered at all!",
    order_id: "1ac4132c",
    rating: 1,
    outlet: "P0082",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback:
      "the sandwich had half meet for some reason. very disappointed and the fries were bot cooked properly either ",
    order_id: "383ee3e4",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Ann Arbor-Cheesesteak Daddy",
    feedback:
      "i ordered the byo cheesesteak, i got to put whatever i wanted on it which was pretty cool. tasted great!",
    order_id: "ae96f4be",
    rating: 5,
    outlet: "P0151",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Clio-House of Parm",
    feedback:
      "the cavatappi with creamy pesto was oustanding! great portion size! super flavorful. will definitely try out other dishes they offer.",
    order_id: "232046e8",
    rating: 5,
    outlet: "P0163",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback: "hair in my food, too much onions",
    order_id: "ba94555d",
    rating: 1,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "the classic breakfast burrito was so fire! hit, fresh and huge portion! cant wait to try another option.",
    order_id: "c6441906",
    rating: 5,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback: "soooooo good! thank you! will be ordering again",
    order_id: "ef6957fd",
    rating: 5,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      " spicy penne alla vodka was really good.  i added chicken and the portion was solid ",
    order_id: "157dffa2",
    rating: 5,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    feedback:
      "flavor was great on the basic b*tch bowl. the hint of sun dried tomatoes was perfect.",
    order_id: "e0cd814a",
    rating: 5,
    outlet: "P0201",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-House of Parm",
    feedback:
      "the spaghetti was broken down to vermicelli length! sauce is subpar. ",
    order_id: "28cfec9a",
    rating: 2,
    outlet: "P0202",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Pop s Meatball Sandwich",
    feedback: "all i recieved were chciken wings",
    order_id: "696422ae",
    rating: 1,
    outlet: "P0203",
    channel: "DOORDASH",
  },
  {
    name: "Classic Lanes-Cheeky Bird",
    feedback:
      "this place is the bees knees\nabsolute awesome sauce yummy goodness!",
    order_id: "a5ec4f46",
    rating: 5,
    outlet: "P0241",
    channel: "DOORDASH",
  },
  {
    name: "Classic Lanes-Cheeky Bird",
    feedback:
      "the cajun cluck was oustanding! tasty as can be. will definitely order this again.",
    order_id: "6d53391b",
    rating: 5,
    outlet: "P0241",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "the sheesehead had no cheese and extra things were added that were not listed as included toppings. what a shame",
    order_id: "6c32c876",
    rating: 1,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "ordered two wake n bake burritos, did not come with ground beef like listed, what's going on??",
    order_id: "abdd26fe",
    rating: 3,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Fifth Avenue-Pop s Meatball Sandwich",
    feedback:
      "first time I've ordered from you guys. overall food was good except for the meatballs. they tasted like they were made yesterday and they were very dry and right. the role the cheese and the sauce were all very good as well as the brownie. The cookie not so much. ",
    order_id: "dc506cb5",
    rating: 3,
    outlet: "P0092",
    channel: "UBEREATS",
  },
  {
    name: "Good Vibes Lounge-Cheesesteak Daddy",
    feedback: "food was dry over cook ",
    order_id: "247e351e",
    rating: 1,
    outlet: "P0061",
    channel: "UBEREATS",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "Order never arrived! ",
    order_id: "4b923a08",
    rating: 1,
    outlet: "P0051",
    channel: "UBEREATS",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback: "   there was a big chunk of fat in the  Steak",
    order_id: "b053a063",
    rating: 5,
    outlet: "P0041",
    channel: "UBEREATS",
  },
  {
    name: "Bigtime Market-Cheesesteak Daddy",
    feedback:
      "   I didn't like the texture. I think this is just personal preference.",
    order_id: "b122d46b",
    rating: 5,
    outlet: "P0021",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "the classic breakfast bowl was good but skimpy on the breakfast meat",
    order_id: "b4cda4ab",
    rating: 4,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      "the food was horrible!!! do not do it!!! the pasta wasn't drained and it was watery and a 5 year old could have made that!",
    order_id: "fc69de99",
    rating: 1,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "i received the wrong item. the item i received was terrible. the side of cheese sauce was canned nacho cheese. i would not recommend.",
    order_id: "c16b0edf",
    rating: 1,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Good Vibes Lounge-Cheesesteak Daddy",
    feedback: "just not what i thought it would look like or taste like.",
    order_id: "2c48f872",
    rating: 1,
    outlet: "P0061",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback: "Seriously good! Will be ordering again!",
    order_id: "2c591bda",
    rating: 5,
    outlet: "P0081",
    channel: "GRUBHUB",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      "the fettuccine alfredo cost almost $20 and was the size of a lean cuisine. it was tiny.  ",
    order_id: "8dbe8f6b",
    rating: 1,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "i've ordered from here twice and and haven't gotten meat on my burrito either time. lot of potential if they can get their orders right",
    order_id: "0ea5f1d9",
    rating: 2,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback: "way to expensive not even good ",
    order_id: "6d442d05",
    rating: 1,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Orange Tree Cafe Restaurant-House of Parm",
    feedback:
      "terrible!  we paid the $6 upcharge for two pasta dishes and no chicken was included. the pasta dishes were overcooked and bland. save your money and eat elsewhere.",
    order_id: "174f174d",
    rating: 1,
    outlet: "P0252",
    channel: "DOORDASH",
  },
  {
    name: "Cameo Restaurant-Bedhead Burritos and Bowls",
    feedback:
      "forgot my cream cheese and the oj spilled all over everything so can't even eat it. ",
    order_id: "ae03aa4d",
    rating: 1,
    outlet: "P0231",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "items were not included in my order aaand items were not as described either. ordered a bagel with cream cheese and didn't get the cream cheese. ordered the basic b*tch bowl and received hash browns instead of tots. i was very disappointed. won't be coming back.",
    order_id: "6ad78e80",
    rating: 1,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "The Beach Tiki Bar-Cheesesteak Daddy",
    feedback:
      "cheesehead came with no kraut, no onions, no whiz, pretty much nothing that was in the description. it did come with macaroni bites on the sandwhich. so kudos for trying",
    order_id: "967e78a5",
    rating: 2,
    outlet: "P0131",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Clio-Bedhead Burritos and Bowls",
    feedback:
      "the classic breakfast burrito slaps! so fire!!! hot, tasty and fast delivery! ",
    order_id: "885c7e32",
    rating: 5,
    outlet: "P0161",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "these burritos are the bomb.com\n3rd time ordering and its been amazing every time!",
    order_id: "0ccf9092",
    rating: 5,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      "this was delicious, that sauce is incredible. lemony and good portion of chicken too!",
    order_id: "026cfd7b",
    rating: 5,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Pop s Meatball Sandwich",
    feedback: "good i guess.",
    order_id: "61f983a0",
    rating: 3,
    outlet: "P0183",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    feedback: "this place is leos on miller",
    order_id: "92a59b41",
    rating: 5,
    outlet: "P0201",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    feedback: "no side of cheese sauce. overall good food!",
    order_id: "d1013016",
    rating: 5,
    outlet: "P0201",
    channel: "DOORDASH",
  },
  {
    name: "Classic Lanes-Cheesesteak Daddy",
    feedback:
      "first time i ordered everything was great but after that my food has been prepared poorly my fries are extremely low for the price i paid i'm very dissatisfied with what i received lately",
    order_id: "a5c0f389",
    rating: 1,
    outlet: "P0242",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-House of Parm",
    feedback: "the chicken marsala is so tasty!! 😋",
    order_id: "1f3860b6",
    rating: 5,
    outlet: "P0272",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Pop s Meatball Sandwich",
    feedback: "Absolutely delicious  ",
    order_id: "48e9ccff",
    rating: 5,
    outlet: "P0052",
    channel: "UBEREATS",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "Absolutely awful  ",
    order_id: "357f474f",
    rating: 1,
    outlet: "P0051",
    channel: "UBEREATS",
  },
  {
    name: "Bigtime Market-Pop s Meatball Sandwich",
    feedback: "   The meatballs were too salty, but still tasted great.",
    order_id: "e967952a",
    rating: 5,
    outlet: "P0022",
    channel: "UBEREATS",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheeky Bird",
    feedback: "   only got 1 of my 3 sandwhiches",
    order_id: "50cf8c7c",
    rating: 1,
    outlet: "P0053",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Michigan-Pop s Meatball Sandwich",
    feedback: "food was ice cold when it arrived 2 hours later  ",
    order_id: "388eebbc",
    rating: 1,
    outlet: "P0273",
    channel: "UBEREATS",
  },
  {
    name: "Classic Lanes-Cheesesteak Daddy",
    feedback: "   s",
    order_id: "aedd0f08",
    rating: 2,
    outlet: "P0242",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "the meals were all sent vegetarian and what we chose was all supposed to have meat. not worthy the price paid and very disappointing  ",
    order_id: "82094507",
    rating: 2,
    outlet: "P0181",
    channel: "UBEREATS",
  },
  {
    name: "Orange Tree Cafe Restaurant-Bedhead Burritos and Bowls",
    feedback:
      "the basic b*tch bowl was outstanding! fresh and tastyyy! can't wait to try some of the other options.",
    order_id: "dc9d64cf",
    rating: 5,
    outlet: "P0251",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    feedback:
      "this burrito was delicious, cooked to perfection and you can tell all the ingredients are super fresh. will be back for more. ",
    order_id: "c3c6a5a1",
    rating: 5,
    outlet: "P0201",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-House of Parm",
    feedback: "alfredo was bland but better than the green stuff ",
    order_id: "f8a518f4",
    rating: 2,
    outlet: "P0272",
    channel: "DOORDASH",
  },
  {
    name: "Cameo Restaurant-House of Parm",
    feedback:
      "wow! this place is amazing! i tried the fettuccine alfredo and the meatball parmesan sandwich. both were so delicious! great size portions and well worth the money spent. ill be back house of parm! ",
    order_id: "a8d639fe",
    rating: 5,
    outlet: "P0232",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "not worth the price. eggs in both the burrito and the bowl were flavorous rubber. so little sausage in the burrito that couldn't even get some in every bite. hasbrowns undercooked. everything was very bland. only positive were the tots were crispy in the bowl.",
    order_id: "3d54e27b",
    rating: 2,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Cameo Restaurant-House of Parm",
    feedback: "this place is amazinggggg",
    order_id: "84a54c10",
    rating: 5,
    outlet: "P0232",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback: "wrong burrito",
    order_id: "dd27aad8",
    rating: 4,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Pop s Meatball Sandwich",
    feedback: "in my personal opinion, a complete rip off for the price",
    order_id: "986cfc52",
    rating: 1,
    outlet: "P0183",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "the burritos were not even what the description said. none of the promised ingredients. barely anything on them for the cost. it's like a $5 burrito for $14. i paid for extra sausage for my son and maybe got a link's worth cut up on top...for over $2 paid. way over priced and not what is advertised. ",
    order_id: "0f9f57e2",
    rating: 1,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback:
      "i have ordered from here a few times now and its been great every time for the pasta fix",
    order_id: "9a550fde",
    rating: 5,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback:
      'the philly was incredibly dry and was very small for the price, maybe 10" they also forgot the side of cheese sauce which probably would have helped. for the frings (half fries, half onion rings) im not convinced there were even onions in the onion rings it was all batter and the fries were undercooked and didnt have any salt or anything on them. ',
    order_id: "cfa59251",
    rating: 1,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Cameo Restaurant-House of Parm",
    feedback: "great tasting food, but very small quantities for the price.",
    order_id: "38a24563",
    rating: 3,
    outlet: "P0232",
    channel: "DOORDASH",
  },
  {
    name: "Overtyme Bar & Grill-Cheesesteak Daddy",
    feedback:
      " the frito bandito was so fire!!! try this spot immediately.. you won't regret it.",
    order_id: "1167c546",
    rating: 5,
    outlet: "P0031",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Pop s Meatball Sandwich",
    feedback:
      "the pop's original was perfect! best meatball sandwich i have ever had!! thank you pop!",
    order_id: "ca6e0998",
    rating: 5,
    outlet: "P0102",
    channel: "DOORDASH",
  },
  {
    name: "Bigtime Market-Cheesesteak Daddy",
    feedback: "delicious! great portions. will definitely get this again!",
    order_id: "75c5f899",
    rating: 5,
    outlet: "P0021",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "dry as heck not seasoned enough bland ",
    order_id: "528086cc",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "delicious! highly recommend!!!",
    order_id: "3c0ef743",
    rating: 5,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Cheesesteak Daddy",
    feedback:
      "more onions than meat. fixings fell out of bottom of bun when picked up. not worth the price.",
    order_id: "d5942503",
    rating: 2,
    outlet: "P0071",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheesesteak Daddy",
    feedback:
      "the philly po' boy and the frito bandito were so fire!!! fast and fresh. will be reordering! thanks daddy",
    order_id: "e59d1579",
    rating: 5,
    outlet: "P0081",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Cheesesteak Daddy",
    feedback: "completely satisfied all my food was right and very delicious￼",
    order_id: "f6f0f8ef",
    rating: 5,
    outlet: "P0101",
    channel: "DOORDASH",
  },
  {
    name: "Johnnys On The Lake -Pop s Meatball Sandwich",
    feedback: "sandwich was really good and the side of fries is huge!",
    order_id: "54ad509b",
    rating: 5,
    outlet: "P0072",
    channel: "DOORDASH",
  },
  {
    name: "Detroit Grille House-Cheesesteak Daddy",
    feedback: "loved!! cheesy, juicy and tender!!! great portions too",
    order_id: "5744cf52",
    rating: 5,
    outlet: "P0101",
    channel: "DOORDASH",
  },
  {
    name: "Good Vibes Lounge-Cheesesteak Daddy",
    feedback:
      "overall the sandwich was good. the only issue i had with the sandwich was the spring lettuce salad that was placed on top of it. it made the sandwich hard to eat . i suggest chopping up your greens a little.",
    order_id: "4f02b6a4",
    rating: 3,
    outlet: "P0061",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Dearborn-Cheesesteak Daddy",
    feedback: "if i can rate a 0 i would don't order this bro ",
    order_id: "a2f02c9b",
    rating: 1,
    outlet: "P0051",
    channel: "DOORDASH",
  },
  {
    name: "Bigtime Market-Cheesesteak Daddy",
    feedback:
      "the pizza steak was excellent. the bread they use is killer. four stars only because it didnt have nearly enough pizza sauce      ",
    order_id: "f4264801",
    rating: 4,
    outlet: "P0021",
    channel: "DOORDASH",
  },
  {
    name: "Gator Jakes Bar & Grill-Cheesesteak Daddy",
    feedback: "half of the order was wrong, and the food was terrible ",
    order_id: "1a868483",
    rating: 1,
    outlet: "P0111",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Ann Arbor-Cheeky Bird",
    feedback:
      "cajun cluck, good name but even better food. definitely worth it!",
    order_id: "92c6edb1",
    rating: 5,
    outlet: "P0153",
    channel: "DOORDASH",
  },
  {
    name: "Southgate Grill-Cheesesteak Daddy",
    feedback: "i ordered a brownie and cheese sauce and didn't get either",
    order_id: "929c7172",
    rating: 1,
    outlet: "P0041",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Clio-Cheeky Bird",
    feedback: "great sandwich. didn't get my cookie",
    order_id: "8a0f5089",
    rating: 3,
    outlet: "P0162",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback: "awesome!! love breakfast burritos - this was great",
    order_id: "b87b35c2",
    rating: 5,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback: "just enough buffalo sauce, very good!",
    order_id: "e07779bb",
    rating: 5,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-House of Parm",
    feedback: "chicken was nasty and meal for the price was tiny!",
    order_id: "4af3170e",
    rating: 1,
    outlet: "P0182",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    feedback:
      "food was really tasty!! i had the wake n' bake burrito - onions were really flavorful",
    order_id: "addc955f",
    rating: 5,
    outlet: "P0201",
    channel: "DOORDASH",
  },
  {
    name: "Classic Lanes-Cheesesteak Daddy",
    feedback:
      "tasty af! great quality ingredients, not super greasy, good portions. will be ordering again!",
    order_id: "81df2e08",
    rating: 5,
    outlet: "P0242",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback: "mostly egg. barely any sauce. bland sausage",
    order_id: "54ac60df",
    rating: 2,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "US 12 Bar and Grill-Pop s Meatball Sandwich",
    feedback:
      "Only a few meatballs and little sauce. The second time was not as good as the first  ",
    order_id: "f5f53465",
    rating: 2,
    outlet: "P0142",
    channel: "UBEREATS",
  },
  {
    name: "The Beach Tiki Bar-Cheesesteak Daddy",
    feedback:
      "Wrong item sent but food was delicious , Was replaced with a cookie, not what I ordered., Hot and delicious, well seasoned and full of flavor. Fries were crispy and seasoned just right.",
    order_id: "b2617e69",
    rating: 4,
    outlet: "P0131",
    channel: "UBEREATS",
  },
  {
    name: "The Beach Tiki Bar-Cheesesteak Daddy",
    feedback:
      "everything was cold :( we threw everything out wont be back again ",
    order_id: "d0710e75",
    rating: 3,
    outlet: "P0131",
    channel: "UBEREATS",
  },
  {
    name: "Good Vibes Lounge-Cheesesteak Daddy",
    feedback: "   reguested brownie was sent cookies...",
    order_id: "f615275a",
    rating: 4,
    outlet: "P0061",
    channel: "UBEREATS",
  },
  {
    name: "Overtyme Bar & Grill-Cheesesteak Daddy",
    feedback:
      "ordered a combo with mac and cheese wedges didn't get them. also order took so long the bread was hard and cold. sad I was really looking forward to trying here. , was also missing a item ",
    order_id: "0bd146c5",
    rating: 3,
    outlet: "P0031",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "I wasn't given the correct meal. I order a $17.35 bowl not a 9.99 burrito.  ",
    order_id: "205c8830",
    rating: 1,
    outlet: "P0271",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "no buffalo sauce. definitely no double bacon. eggs didn't taste great.",
    order_id: "5fbee46d",
    rating: 2,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Orange Tree Cafe Restaurant-House of Parm",
    feedback:
      "tried the spicy penne alla vodka and the chicken limone with cavatappi! fire! this place slaps!! give it a try",
    order_id: "e5f6670f",
    rating: 5,
    outlet: "P0252",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Ypsilanti-Bedhead Burritos and Bowls",
    feedback:
      "the basic b*tch bowl was outstanding! huge portion! hot, tasty and delicious. cant wait to try another one of their options",
    order_id: "13ea3d20",
    rating: 5,
    outlet: "P0261",
    channel: "DOORDASH",
  },
  {
    name: "Leo s Coney Island - Miller Rd-Bedhead Burritos and Bowls",
    feedback:
      "would never order again. the food tasted okay, but not worth the amount money at all. there was also a plastic bread tie in the burrito.",
    order_id: "73870995",
    rating: 1,
    outlet: "P0201",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-Ann Arbor-Pop s Meatball Sandwich",
    feedback:
      "disappointed. no cheese on the sandwich and i didn't opt to remove it. for the price, it really didn't seem worth it even if it had had the cheese. for a sandwich that is supposed to be covered with soup, or come with soup? the photos are misleading, it was very dry. probably will not order again considering the high price point.",
    order_id: "9709fd07",
    rating: 2,
    outlet: "P0152",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "both burritos were supposed to have tots in them and we did not receive extra order of hash browns",
    order_id: "b301072e",
    rating: 3,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Michigan-Bedhead Burritos and Bowls",
    feedback:
      "eggs were dry. eggs came with hot sauce, which was not in the description. very disappointing ",
    order_id: "03753c59",
    rating: 2,
    outlet: "P0271",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "small portion, bland, added bacon and barely had 5 bacon bit sized pieces",
    order_id: "1fa96867",
    rating: 1,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Red Olive Restaurant - Ferndale-Bedhead Burritos and Bowls",
    feedback:
      "paid $3.49 for orange juice have the tiniest cup in the world and with apple juice. i want my money back this is ridiculous.",
    order_id: "f7e8cd64",
    rating: 1,
    outlet: "P0181",
    channel: "DOORDASH",
  },
  {
    name: "Cameo Restaurant-Bedhead Burritos and Bowls",
    feedback:
      "the wake n' bake burrito slapped hard. definitely a good snack for after a sesh! really lives up to its name!",
    order_id: "9dc45dc9",
    rating: 5,
    outlet: "P0231",
    channel: "DOORDASH",
  },
  {
    name: "Leos Coney Island-West Bloomfield-Cheeky Bird",
    feedback:
      "no marinara sauce on my chicken parm.  no drink either. , No marinara sauce.",
    order_id: "13da0dba",
    rating: 1,
    outlet: "P0083",
    channel: "UBEREATS",
  },
  {
    name: "Red Olive Restaurant - Michigan-House of Parm",
    feedback:
      "part of my order did not arrive and no one answered when i called for a refund on that part of the order. ",
    order_id: "ed1c0e9d",
    rating: 1,
    outlet: "P0272",
    channel: "DOORDASH",
  },
];

const saveText = ({ payload, file_name }) => {
  try {
    fs.appendFileSync(
      path.join(path.resolve("./"), "/sample", `${'sample'}.txt`),
      `\n${payload}`,
      "UTF8"
    );
  } catch (error) {
    return {
      status: false,
      error: error,
    };
  }
};

// get bad reviews

const badReviews = reviews.filter((review) => review.rating < 3);
const x = badReviews.map((i) => `${i.feedback}`);

const sample = [
  "i didn't get my food i didn't even get the right restaurant ",
  "way to salty! waaayy to salty and the fries are plain. they tasted like mcdonald's fries with no salt left over night. ",
  "nothing was right and got no refund",
  "they sent me meat on bread. i ordered the cheesehead. if you are thinking of ordering here dont. 3rd time this week. if you walk in they are fine. you order on doordash forget it. your order will 100% wrong or not what you wanted. youve been warned ",
  "will not again order from here.  the phili was so salty i couldn't eat it.  i ordered double the meat, which the meat was so dried out.  there are better cheese steaks at gas stations.  i also ordered a coke, which ended up being a $3 can of coke.  an absolute waste of money!!!",
  "order was wrong, $60 but $13 refund. garbage. save y money.",
  "i got a marinara meatball sub",
  "burnt onions rings hair in sandwich ",
  "don't pay for anything extra like extra cheese or toppings cause they won't add it to your food.",
  "it was too salty never will order from this place again",
  "lowkey wasn't that good, made me wanna finish it as fast as i can .",
  "sent the wrong order and doordash now takes 24 hours to even fix it this is a complete joke",
  "hard and dry ",
  "frito bandito and cheesesteak daddy were terrible ",
  "food was horrible sandwitch was ashes and my fries was frozen ",
  "only giving one star because it wasn't an option for none..... steak extremely overcooked/burnt and dry.... tried to submit a complaint with no response and no one answers the phone number listed.... definitely won't order ever again",
  "didn't get the right order",
  "only me combo does  not match description. small portion size no cheese i literally got the one with cheese and it has no cheese trying to get them to pick up i want refund",
  "i ordered the cheese head. in all fairness i did remove the onion and sourcraut, but what i received was barely a cheesesteak. of course it's not going to be overflowing like in the picture, but i at least expected it to be a decent amount of meat, even with the sourcraut removed. i wasn't expecting extra meat, but this sandwich is pathetic.",
  "the sandwich i received is not what i ordered, and on top of it the sandwich they did send me the meat is over cooked and dry. for the amount of time i had to wait past the estimated delivery time they could have gotten a one sandwich order correct. first time ordering, and is most likely the last unfortunately. ",
  "meat and buns were way overcooked.  entire meal was ruined, had to pick out what was edible off the top of the packs of meat.",
  "there was no meat in the burrito and the bagel was super super dry :/",
  "i upgraded to Onion rings and still got fries ",
  "   mid",
  "   everything inside of the burrito tasted stale or rotten. i couldn't even finish the first bite",
  "food cane cold and they did not even care to remake and sent hour hold??!! ",
  "   the promotion didnt work ",
  "burrito had no eggs, beef, or cheese. came with just tots and onions. was so disappointing after they took an extra 20 minutes beyond what was promised.",
  "actually leo's, overcooked, appetizer sized 20$ diner bull****",
  "wasn't a fan. ",
  "the quality of food was awful. the burritos mostly consist of the wrap and not enough filling. the side of hashbrowns were burnt and tasted very off. would not recommend.  ",
  "first time trying this place and my burrito is missing half the ingredients lol..",
  "The pasta taste like it was very undercooked and it was very chalky and pasty. And for $18. I expected a little bit more on the portion. ",
  "This is not really chicken marsala. It's a mushrooms sauce on fettuccine, with a salty, dry, grilled chicken breast on the top.  I was duped. Now you know.",
  "1st time trying this. they messed up the order and switched the burritos around.",
  "they made the wrong sandwich no lettuce no tomatoe no extra cheese.. and wayyyyy to much garlic",
  "ordered a pop's original and it should have had tomato sauce and provolone cheese.  sub came plain with some kind of yellow cheese.  not what i ordered at all!",
  "the sandwich had half meet for some reason. very disappointed and the fries were bot cooked properly either ",
  "hair in my food, too much onions",
  "the spaghetti was broken down to vermicelli length! sauce is subpar. ",
  "all i recieved were chciken wings",
  "the sheesehead had no cheese and extra things were added that were not listed as included toppings. what a shame",
  "food was dry over cook ",
  "Order never arrived! ",
  "the food was horrible!!! do not do it!!! the pasta wasn't drained and it was watery and a 5 year old could have made that!",
  "i received the wrong item. the item i received was terrible. the side of cheese sauce was canned nacho cheese. i would not recommend.",
  "just not what i thought it would look like or taste like.",
  "the fettuccine alfredo cost almost $20 and was the size of a lean cuisine. it was tiny.  ",
  "i've ordered from here twice and and haven't gotten meat on my burrito either time. lot of potential if they can get their orders right",
  "way to expensive not even good ",
  "terrible!  we paid the $6 upcharge for two pasta dishes and no chicken was included. the pasta dishes were overcooked and bland. save your money and eat elsewhere.",
  "forgot my cream cheese and the oj spilled all over everything so can't even eat it. ",
  "items were not included in my order aaand items were not as described either. ordered a bagel with cream cheese and didn't get the cream cheese. ordered the basic b*tch bowl and received hash browns instead of tots. i was very disappointed. won't be coming back.",
  "cheesehead came with no kraut, no onions, no whiz, pretty much nothing that was in the description. it did come with macaroni bites on the sandwhich. so kudos for trying",
  "first time i ordered everything was great but after that my food has been prepared poorly my fries are extremely low for the price i paid i'm very dissatisfied with what i received lately",
  "Absolutely awful  ",
  "   only got 1 of my 3 sandwhiches",
  "food was ice cold when it arrived 2 hours later  ",
  "   s",
  "the meals were all sent vegetarian and what we chose was all supposed to have meat. not worthy the price paid and very disappointing  ",
  "alfredo was bland but better than the green stuff ",
  "not worth the price. eggs in both the burrito and the bowl were flavorous rubber. so little sausage in the burrito that couldn't even get some in every bite. hasbrowns undercooked. everything was very bland. only positive were the tots were crispy in the bowl.",
  "in my personal opinion, a complete rip off for the price",
  "the burritos were not even what the description said. none of the promised ingredients. barely anything on them for the cost. it's like a $5 burrito for $14. i paid for extra sausage for my son and maybe got a link's worth cut up on top...for over $2 paid. way over priced and not what is advertised. ",
  'the philly was incredibly dry and was very small for the price, maybe 10" they also forgot the side of cheese sauce which probably would have helped. for the frings (half fries, half onion rings) im not convinced there were even onions in the onion rings it was all batter and the fries were undercooked and didnt have any salt or anything on them. ',
  "dry as heck not seasoned enough bland ",
  "more onions than meat. fixings fell out of bottom of bun when picked up. not worth the price.",
  "if i can rate a 0 i would don't order this bro ",
  "half of the order was wrong, and the food was terrible ",
  "i ordered a brownie and cheese sauce and didn't get either",
  "chicken was nasty and meal for the price was tiny!",
  "mostly egg. barely any sauce. bland sausage",
  "Only a few meatballs and little sauce. The second time was not as good as the first  ",
  "I wasn't given the correct meal. I order a $17.35 bowl not a 9.99 burrito.  ",
  "no buffalo sauce. definitely no double bacon. eggs didn't taste great.",
  "would never order again. the food tasted okay, but not worth the amount money at all. there was also a plastic bread tie in the burrito.",
  "disappointed. no cheese on the sandwich and i didn't opt to remove it. for the price, it really didn't seem worth it even if it had had the cheese. for a sandwich that is supposed to be covered with soup, or come with soup? the photos are misleading, it was very dry. probably will not order again considering the high price point.",
  "eggs were dry. eggs came with hot sauce, which was not in the description. very disappointing ",
  "small portion, bland, added bacon and barely had 5 bacon bit sized pieces",
  "paid $3.49 for orange juice have the tiniest cup in the world and with apple juice. i want my money back this is ridiculous.",
  "no marinara sauce on my chicken parm.  no drink either. , No marinara sauce.",
  "part of my order did not arrive and no one answered when i called for a refund on that part of the order. ",
];
